<?php

namespace avadim\FastExcelReader\Xls;

/**
 * Built-in function names by their BIFF index
 *
 * A formula stores the function it calls as a number, so rendering the formula
 * back to text needs this table. An index that is missing here cannot be
 * rendered faithfully, and the decompiler gives up on the whole formula rather
 * than emit a wrong name.
 */
final class BiffFunction
{
    /**
     * @var array<int, string>
     */
    public const NAMES = [
        0 => 'COUNT',
        1 => 'IF',
        2 => 'ISNA',
        3 => 'ISERROR',
        4 => 'SUM',
        5 => 'AVERAGE',
        6 => 'MIN',
        7 => 'MAX',
        8 => 'ROW',
        9 => 'COLUMN',
        10 => 'NA',
        11 => 'NPV',
        12 => 'STDEV',
        13 => 'DOLLAR',
        14 => 'FIXED',
        15 => 'SIN',
        16 => 'COS',
        17 => 'TAN',
        18 => 'ATAN',
        19 => 'PI',
        20 => 'SQRT',
        21 => 'EXP',
        22 => 'LN',
        23 => 'LOG10',
        24 => 'ABS',
        25 => 'INT',
        26 => 'SIGN',
        27 => 'ROUND',
        28 => 'LOOKUP',
        29 => 'INDEX',
        30 => 'REPT',
        31 => 'MID',
        32 => 'LEN',
        33 => 'VALUE',
        34 => 'TRUE',
        35 => 'FALSE',
        36 => 'AND',
        37 => 'OR',
        38 => 'NOT',
        39 => 'MOD',
        40 => 'DCOUNT',
        41 => 'DSUM',
        42 => 'DAVERAGE',
        43 => 'DMIN',
        44 => 'DMAX',
        45 => 'DSTDEV',
        46 => 'VAR',
        47 => 'DVAR',
        48 => 'TEXT',
        49 => 'LINEST',
        50 => 'TREND',
        51 => 'LOGEST',
        52 => 'GROWTH',
        56 => 'PV',
        57 => 'FV',
        58 => 'NPER',
        59 => 'PMT',
        60 => 'RATE',
        61 => 'MIRR',
        62 => 'IRR',
        63 => 'RAND',
        64 => 'MATCH',
        65 => 'DATE',
        66 => 'TIME',
        67 => 'DAY',
        68 => 'MONTH',
        69 => 'YEAR',
        70 => 'WEEKDAY',
        71 => 'HOUR',
        72 => 'MINUTE',
        73 => 'SECOND',
        74 => 'NOW',
        75 => 'AREAS',
        76 => 'ROWS',
        77 => 'COLUMNS',
        78 => 'OFFSET',
        82 => 'SEARCH',
        83 => 'TRANSPOSE',
        86 => 'TYPE',
        97 => 'ATAN2',
        98 => 'ASIN',
        99 => 'ACOS',
        100 => 'CHOOSE',
        101 => 'HLOOKUP',
        102 => 'VLOOKUP',
        105 => 'ISREF',
        109 => 'LOG',
        111 => 'CHAR',
        112 => 'LOWER',
        113 => 'UPPER',
        114 => 'PROPER',
        115 => 'LEFT',
        116 => 'RIGHT',
        117 => 'EXACT',
        118 => 'TRIM',
        119 => 'REPLACE',
        120 => 'SUBSTITUTE',
        121 => 'CODE',
        124 => 'FIND',
        125 => 'CELL',
        126 => 'ISERR',
        127 => 'ISTEXT',
        128 => 'ISNUMBER',
        129 => 'ISBLANK',
        130 => 'T',
        131 => 'N',
        140 => 'DATEVALUE',
        141 => 'TIMEVALUE',
        142 => 'SLN',
        143 => 'SYD',
        144 => 'DDB',
        148 => 'INDIRECT',
        162 => 'CLEAN',
        163 => 'MDETERM',
        164 => 'MINVERSE',
        165 => 'MMULT',
        167 => 'IPMT',
        168 => 'PPMT',
        169 => 'COUNTA',
        183 => 'PRODUCT',
        184 => 'FACT',
        189 => 'DPRODUCT',
        190 => 'ISNONTEXT',
        193 => 'STDEVP',
        194 => 'VARP',
        195 => 'DSTDEVP',
        196 => 'DVARP',
        197 => 'TRUNC',
        198 => 'ISLOGICAL',
        199 => 'DCOUNTA',
        204 => 'USDOLLAR',
        205 => 'FINDB',
        206 => 'SEARCHB',
        207 => 'REPLACEB',
        208 => 'LEFTB',
        209 => 'RIGHTB',
        210 => 'MIDB',
        211 => 'LENB',
        212 => 'ROUNDUP',
        213 => 'ROUNDDOWN',
        214 => 'ASC',
        215 => 'DBCS',
        216 => 'RANK',
        219 => 'ADDRESS',
        220 => 'DAYS360',
        221 => 'TODAY',
        222 => 'VDB',
        227 => 'MEDIAN',
        228 => 'SUMPRODUCT',
        229 => 'SINH',
        230 => 'COSH',
        231 => 'TANH',
        232 => 'ASINH',
        233 => 'ACOSH',
        234 => 'ATANH',
        235 => 'DGET',
        244 => 'INFO',
        247 => 'DB',
        252 => 'FREQUENCY',
        261 => 'ERROR.TYPE',
        269 => 'AVEDEV',
        270 => 'BETADIST',
        271 => 'GAMMALN',
        272 => 'BETAINV',
        273 => 'BINOMDIST',
        274 => 'CHIDIST',
        275 => 'CHIINV',
        276 => 'COMBIN',
        277 => 'CONFIDENCE',
        278 => 'CRITBINOM',
        279 => 'EVEN',
        280 => 'EXPONDIST',
        281 => 'FDIST',
        282 => 'FINV',
        283 => 'FISHER',
        284 => 'FISHERINV',
        285 => 'FLOOR',
        286 => 'GAMMADIST',
        287 => 'GAMMAINV',
        288 => 'CEILING',
        289 => 'HYPGEOMDIST',
        290 => 'LOGNORMDIST',
        291 => 'LOGINV',
        292 => 'NEGBINOMDIST',
        293 => 'NORMDIST',
        294 => 'NORMSDIST',
        295 => 'NORMINV',
        296 => 'NORMSINV',
        297 => 'STANDARDIZE',
        298 => 'ODD',
        299 => 'PERMUT',
        300 => 'POISSON',
        301 => 'TDIST',
        302 => 'WEIBULL',
        303 => 'SUMXMY2',
        304 => 'SUMX2MY2',
        305 => 'SUMX2PY2',
        306 => 'CHITEST',
        307 => 'CORREL',
        308 => 'COVAR',
        309 => 'FORECAST',
        310 => 'FTEST',
        311 => 'INTERCEPT',
        312 => 'PEARSON',
        313 => 'RSQ',
        314 => 'STEYX',
        315 => 'SLOPE',
        316 => 'TTEST',
        317 => 'PROB',
        318 => 'DEVSQ',
        319 => 'GEOMEAN',
        320 => 'HARMEAN',
        321 => 'SUMSQ',
        322 => 'KURT',
        323 => 'SKEW',
        324 => 'ZTEST',
        325 => 'LARGE',
        326 => 'SMALL',
        327 => 'QUARTILE',
        328 => 'PERCENTILE',
        329 => 'PERCENTRANK',
        330 => 'MODE',
        331 => 'TRIMMEAN',
        332 => 'TINV',
        336 => 'CONCATENATE',
        337 => 'POWER',
        342 => 'RADIANS',
        343 => 'DEGREES',
        344 => 'SUBTOTAL',
        345 => 'SUMIF',
        346 => 'COUNTIF',
        347 => 'COUNTBLANK',
        350 => 'ISPMT',
        351 => 'DATEDIF',
        352 => 'DATESTRING',
        353 => 'NUMBERSTRING',
        354 => 'ROMAN',
        358 => 'GETPIVOTDATA',
        359 => 'HYPERLINK',
        360 => 'PHONETIC',
        361 => 'AVERAGEA',
        362 => 'MAXA',
        363 => 'MINA',
        364 => 'STDEVPA',
        365 => 'VARPA',
        366 => 'STDEVA',
        367 => 'VARA',
    ];

    /**
     * @param int $index
     *
     * @return string|null
     */
    public static function name(int $index): ?string
    {
        return self::NAMES[$index] ?? null;
    }
}
