<?php

declare(strict_types=1);

namespace avadim\FastExcelReader\Tests\Support;

use PHPUnit\Framework\TestCase;

/**
 * Base class for the refactoring safety net.
 *
 * Pins everything environment-dependent so that snapshots stay portable between
 * machines. Excel::__construct() builds its builtin date formats from
 * IntlDateFormatter using the default locale, and stores the default timezone,
 * so an unpinned locale silently bakes machine-specific date patterns into the
 * expected values.
 */
abstract class GuardTestCase extends TestCase
{
    public const DEMO_DIR = __DIR__ . '/../../demo/files/';
    public const TEST_FILES_DIR = __DIR__ . '/../test_files/';
    public const SNAPSHOT_DIR = __DIR__ . '/../snapshots/';

    /** @var string|null */
    private $originalLocale;

    /** @var string|null */
    private $originalTimezone;

    protected function setUp(): void
    {
        parent::setUp();

        $this->originalTimezone = date_default_timezone_get();
        date_default_timezone_set('UTC');

        if (class_exists('\Locale', false)) {
            $this->originalLocale = \Locale::getDefault();
            \Locale::setDefault('en_US');
        }
    }

    protected function tearDown(): void
    {
        if ($this->originalTimezone !== null) {
            date_default_timezone_set($this->originalTimezone);
        }
        if ($this->originalLocale !== null) {
            \Locale::setDefault($this->originalLocale);
        }

        parent::tearDown();
    }

    /**
     * Resolve a fixture name to a full path, looking in both fixture directories
     *
     * @param string $name
     *
     * @return string
     */
    protected static function fixture(string $name): string
    {
        foreach ([self::DEMO_DIR, self::TEST_FILES_DIR] as $dir) {
            if (is_file($dir . $name)) {
                return $dir . $name;
            }
        }

        throw new \RuntimeException('Fixture not found: ' . $name);
    }

    /**
     * Compare a value against its stored snapshot.
     *
     * These are characterization assertions: they state "the behaviour did not
     * change", not "the behaviour is correct". Some snapshots therefore record
     * known quirks on purpose - see the @todo markers in the scenario list.
     *
     * Run with UPDATE_SNAPSHOTS=1 to (re)write snapshots. Never do that to make
     * a failing test pass unless the behaviour change is intended and reviewed.
     *
     * @param string $slug
     * @param mixed $actual
     *
     * @return void
     */
    protected function assertMatchesSnapshot(string $slug, $actual): void
    {
        $file = self::SNAPSHOT_DIR . $slug . '.php';

        if (getenv('UPDATE_SNAPSHOTS')) {
            if (!is_dir(self::SNAPSHOT_DIR)) {
                mkdir(self::SNAPSHOT_DIR, 0777, true);
            }
            file_put_contents($file, "<?php\n\n// Snapshot: {$slug}\n// Generated by RefactorGuardTest. Do not edit by hand.\n\nreturn " . var_export($actual, true) . ";\n");
            $this->addToAssertionCount(1);

            return;
        }

        $this->assertFileExists($file, "Missing snapshot for '{$slug}'. Generate it with UPDATE_SNAPSHOTS=1.");

        $this->assertSame(require $file, $actual, "Snapshot mismatch for '{$slug}'.");
    }
}
