<?php

// Snapshot: area--set-read-area
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  2 => 
  array (
    'B' => 'Pasta',
    'C' => 'Food Paradise Corp.',
    'D' => 1282089600,
  ),
  3 => 
  array (
    'B' => 'Vegetables',
    'C' => 'Foody Stock',
    'D' => 1286928000,
  ),
  4 => 
  array (
    'B' => 'Pasta',
    'C' => 'Horns & Hooves Company',
    'D' => 1327795200,
  ),
  5 => 
  array (
    'B' => 'Vegetables',
    'C' => 'Overseas Company',
    'D' => 1319155200,
  ),
  6 => 
  array (
    'B' => 'Fruits',
    'C' => 'Overseas Company',
    'D' => 1325808000,
  ),
);
