<?php

// Snapshot: area--read-rows-from-then-plain
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  'from' => 
  array (
    2 => 
    array (
      'B' => 'Pasta',
      'C' => 'Food Paradise Corp.',
    ),
    3 => 
    array (
      'B' => 'Vegetables',
      'C' => 'Foody Stock',
    ),
    4 => 
    array (
      'B' => 'Pasta',
      'C' => 'Horns & Hooves Company',
    ),
  ),
  'after' => 
  array (
    2 => 
    array (
      'B' => 'Pasta',
      'C' => 'Food Paradise Corp.',
    ),
    3 => 
    array (
      'B' => 'Vegetables',
      'C' => 'Foody Stock',
    ),
    4 => 
    array (
      'B' => 'Pasta',
      'C' => 'Horns & Hooves Company',
    ),
  ),
);
