<?php

// Snapshot: area--read-first-row-cells-after-area
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  'B2' => 'Pasta',
  'C2' => 'Food Paradise Corp.',
  'D2' => 1282089600,
);
