<?php

// Snapshot: area--from
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  4 => 
  array (
    'C' => 'Date',
    'D' => 'Color',
  ),
  5 => 
  array (
    'C' => 18316800,
    'D' => 'Red',
  ),
  6 => 
  array (
    'C' => -777600,
    'D' => 'Green',
  ),
  7 => 
  array (
    'C' => -62121600,
    'D' => 'Blue',
  ),
  8 => 
  array (
    'C' => 38707200,
    'D' => 'Brown',
  ),
  9 => 
  array (
    'C' => 102729600,
    'D' => 'Yellow',
  ),
  10 => 
  array (
    'C' => -75859200,
    'D' => 'Orange',
  ),
  11 => 
  array (
    'C' => -132969600,
    'D' => 'Purple',
  ),
);
