<?php

// Snapshot: area--area-then-key-mode
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  0 => 
  array (
    0 => 'Date',
    1 => 'Color',
  ),
  1 => 
  array (
    0 => 18316800,
    1 => 'Red',
  ),
  2 => 
  array (
    0 => -777600,
    1 => 'Green',
  ),
  3 => 
  array (
    0 => -62121600,
    1 => 'Blue',
  ),
  4 => 
  array (
    0 => 38707200,
    1 => 'Brown',
  ),
);
