<?php

// Snapshot: area--area-relative
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  4 => 
  array (
    'C' => 'Date',
    'D' => 'Color',
  ),
  5 => 
  array (
    'C' => 18316800,
    'D' => 'Red',
  ),
  6 => 
  array (
    'C' => -777600,
    'D' => 'Green',
  ),
  7 => 
  array (
    'C' => -62121600,
    'D' => 'Blue',
  ),
  8 => 
  array (
    'C' => 38707200,
    'D' => 'Brown',
  ),
);
