<?php

// Snapshot: area--area-then-key-mode
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  0 => 
  array (
    'C' => NULL,
    'D' => NULL,
  ),
  1 => 
  array (
    'C' => NULL,
    'D' => NULL,
  ),
  2 => 
  array (
    'C' => NULL,
    'D' => NULL,
  ),
  3 => 
  array (
    'C' => NULL,
    'D' => NULL,
  ),
  4 => 
  array (
    'C' => NULL,
    'D' => NULL,
  ),
);
