<?php

// Snapshot: area--read-columns-from
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  'B' => 
  array (
    2 => 'Pasta',
    3 => 'Vegetables',
    4 => 'Pasta',
    5 => 'Vegetables',
    6 => 'Fruits',
  ),
  'C' => 
  array (
    2 => 'Food Paradise Corp.',
    3 => 'Foody Stock',
    4 => 'Horns & Hooves Company',
    5 => 'Overseas Company',
    6 => 'Overseas Company',
  ),
  'D' => 
  array (
    2 => 1282089600,
    3 => 1286928000,
    4 => 1327795200,
    5 => 1319155200,
    6 => 1325808000,
  ),
);
