<?php

// Snapshot: area--read-cells-from
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  'B2' => 'Pasta',
  'C2' => 'Food Paradise Corp.',
  'D2' => 1282089600,
  'B3' => 'Vegetables',
  'C3' => 'Foody Stock',
  'D3' => 1286928000,
  'B4' => 'Pasta',
  'C4' => 'Horns & Hooves Company',
  'D4' => 1327795200,
  'B5' => 'Vegetables',
  'C5' => 'Overseas Company',
  'D5' => 1319155200,
  'B6' => 'Fruits',
  'C6' => 'Overseas Company',
  'D6' => 1325808000,
);
