<?php

// Snapshot: area--set-read-area-first-row-keys
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  2 => 
  array (
    'Item' => 'Vermicelli',
    'Category' => 'Pasta',
    'Contractor' => 'Food Paradise Corp.',
    'Date' => 1282089600,
  ),
  3 => 
  array (
    'Item' => 'Eggplant',
    'Category' => 'Vegetables',
    'Contractor' => 'Foody Stock',
    'Date' => 1286928000,
  ),
  4 => 
  array (
    'Item' => 'Spaghetti',
    'Category' => 'Pasta',
    'Contractor' => 'Horns & Hooves Company',
    'Date' => 1327795200,
  ),
  5 => 
  array (
    'Item' => 'Zucchini',
    'Category' => 'Vegetables',
    'Contractor' => 'Overseas Company',
    'Date' => 1319155200,
  ),
  6 => 
  array (
    'Item' => 'Oranges',
    'Category' => 'Fruits',
    'Contractor' => 'Overseas Company',
    'Date' => 1325808000,
  ),
);
