<?php

// Snapshot: cells--plain
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  'A1' => '#',
  'B1' => 'name',
  'C1' => 'birthday',
  'D1' => 'random_int',
  'A2' => 1,
  'B2' => 'James Bond',
  'C2' => -2205187200,
  'D2' => 4573,
  'A3' => 2,
  'B3' => 'Ellen Louise Ripley',
  'C3' => 6614697600,
  'D3' => 982630,
  'A4' => 3,
  'B4' => 'Captain Jack Sparrow',
  'C4' => -6845212800,
  'D4' => 7239,
);
