<?php

// Snapshot: cells--offset-sheet
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  'B2' => 'Data of Sheet1',
  'C2' => NULL,
  'D2' => NULL,
  'B4' => 'Name',
  'C4' => 'Date',
  'D4' => 'Color',
  'B5' => 'Giovanni',
  'C5' => 18316800,
  'D5' => 'Red',
  'B6' => 'James',
  'C6' => -777600,
  'D6' => 'Green',
  'B7' => 'Mateusz',
  'C7' => -62121600,
  'D7' => 'Blue',
  'B8' => 'Francesco',
  'C8' => 38707200,
  'D8' => 'Brown',
  'B9' => 'Miguel',
  'C9' => 102729600,
  'D9' => 'Yellow',
  'B10' => 'Pedro',
  'C10' => -75859200,
  'D10' => 'Orange',
  'B11' => 'Evan',
  'C11' => -132969600,
  'D11' => 'Purple',
);
