<?php

// Snapshot: cells--style-idx
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  'A1' => 
  array (
    'v' => '#',
    's' => 2,
    'f' => NULL,
    't' => 'string',
    'o' => '#',
  ),
  'B1' => 
  array (
    'v' => 'name',
    's' => 2,
    'f' => NULL,
    't' => 'string',
    'o' => 'name',
  ),
  'C1' => 
  array (
    'v' => 'birthday',
    's' => 2,
    'f' => NULL,
    't' => 'string',
    'o' => 'birthday',
  ),
  'D1' => 
  array (
    'v' => 'random_int',
    's' => 2,
    'f' => NULL,
    't' => 'string',
    'o' => 'random_int',
  ),
  'A2' => 
  array (
    'v' => 1,
    's' => 0,
    'f' => NULL,
    't' => 'number',
    'o' => '1',
  ),
  'B2' => 
  array (
    'v' => 'James Bond',
    's' => 0,
    'f' => NULL,
    't' => 'string',
    'o' => 'James Bond',
  ),
  'C2' => 
  array (
    'v' => -2205187200,
    's' => 1,
    'f' => NULL,
    't' => 'date',
    'o' => '45',
  ),
  'D2' => 
  array (
    'v' => 4573,
    's' => 0,
    'f' => NULL,
    't' => 'number',
    'o' => '4573',
  ),
  'A3' => 
  array (
    'v' => 2,
    's' => 0,
    'f' => NULL,
    't' => 'number',
    'o' => '2',
  ),
  'B3' => 
  array (
    'v' => 'Ellen Louise Ripley',
    's' => 0,
    'f' => NULL,
    't' => 'string',
    'o' => 'Ellen Louise Ripley',
  ),
  'C3' => 
  array (
    'v' => 6614697600,
    's' => 1,
    'f' => NULL,
    't' => 'date',
    'o' => '102128',
  ),
  'D3' => 
  array (
    'v' => 982630,
    's' => 0,
    'f' => NULL,
    't' => 'number',
    'o' => '982630',
  ),
  'A4' => 
  array (
    'v' => 3,
    's' => 0,
    'f' => NULL,
    't' => 'number',
    'o' => '3',
  ),
  'B4' => 
  array (
    'v' => 'Captain Jack Sparrow',
    's' => 0,
    'f' => NULL,
    't' => 'string',
    'o' => 'Captain Jack Sparrow',
  ),
  'C4' => 
  array (
    'v' => -6845212800,
    's' => 1,
    'f' => NULL,
    't' => 'date',
    'o' => '31.01.1753',
  ),
  'D4' => 
  array (
    'v' => 7239,
    's' => 0,
    'f' => NULL,
    't' => 'number',
    'o' => '7239',
  ),
);
