<?php

// Snapshot: colkeys--first-row
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  2 => 
  array (
    'Number' => 1,
    'Hero' => 'James Bond',
    'birthday' => -2205187200,
    'Secret' => 4573,
  ),
  3 => 
  array (
    'Number' => 2,
    'Hero' => 'Ellen Louise Ripley',
    'birthday' => 6614697600,
    'Secret' => 982630,
  ),
  4 => 
  array (
    'Number' => 3,
    'Hero' => 'Captain Jack Sparrow',
    'birthday' => -6845212800,
    'Secret' => 7239,
  ),
);
