<?php

// Snapshot: colkeys--row-zero-based
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  0 => 
  array (
    'Number' => '#',
    'Hero' => 'name',
    'C' => 'birthday',
    'Secret' => 'random_int',
  ),
  1 => 
  array (
    'Number' => 1,
    'Hero' => 'James Bond',
    'C' => -2205187200,
    'Secret' => 4573,
  ),
  2 => 
  array (
    'Number' => 2,
    'Hero' => 'Ellen Louise Ripley',
    'C' => 6614697600,
    'Secret' => 982630,
  ),
  3 => 
  array (
    'Number' => 3,
    'Hero' => 'Captain Jack Sparrow',
    'C' => -6845212800,
    'Secret' => 7239,
  ),
);
