<?php

// Snapshot: columns--with-styles
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  'A' => 
  array (
    1 => 
    array (
      'v' => '#',
      's' => 
      array (
        'format' => 
        array (
          'format-num-id' => 0,
          'format-pattern' => 'General',
          'format-category' => 'general',
        ),
        'font' => 
        array (
          'font-size' => '11',
          'font-color' => '#202020',
          'font-name' => 'Calibri',
          'font-family' => '2',
          'font-scheme' => 'minor',
          'font-style-bold' => 1,
          'font-charset' => '204',
        ),
        'fill' => 
        array (
          'fill-pattern' => 'none',
        ),
        'border' => 
        array (
          'border-left-style' => NULL,
          'border-right-style' => NULL,
          'border-top-style' => NULL,
          'border-bottom-style' => NULL,
          'border-diagonal-style' => NULL,
        ),
      ),
      'f' => NULL,
      't' => 'string',
      'o' => '#',
    ),
    2 => 
    array (
      'v' => 1,
      's' => 
      array (
        'format' => 
        array (
          'format-num-id' => 0,
          'format-pattern' => 'General',
          'format-category' => 'general',
        ),
        'font' => 
        array (
          'font-size' => '11',
          'font-color' => '#202020',
          'font-name' => 'Calibri',
          'font-family' => '2',
          'font-scheme' => 'minor',
        ),
        'fill' => 
        array (
          'fill-pattern' => 'none',
        ),
        'border' => 
        array (
          'border-left-style' => NULL,
          'border-right-style' => NULL,
          'border-top-style' => NULL,
          'border-bottom-style' => NULL,
          'border-diagonal-style' => NULL,
        ),
      ),
      'f' => NULL,
      't' => 'number',
      'o' => '1',
    ),
    3 => 
    array (
      'v' => 2,
      's' => 
      array (
        'format' => 
        array (
          'format-num-id' => 0,
          'format-pattern' => 'General',
          'format-category' => 'general',
        ),
        'font' => 
        array (
          'font-size' => '11',
          'font-color' => '#202020',
          'font-name' => 'Calibri',
          'font-family' => '2',
          'font-scheme' => 'minor',
        ),
        'fill' => 
        array (
          'fill-pattern' => 'none',
        ),
        'border' => 
        array (
          'border-left-style' => NULL,
          'border-right-style' => NULL,
          'border-top-style' => NULL,
          'border-bottom-style' => NULL,
          'border-diagonal-style' => NULL,
        ),
      ),
      'f' => NULL,
      't' => 'number',
      'o' => '2',
    ),
    4 => 
    array (
      'v' => 3,
      's' => 
      array (
        'format' => 
        array (
          'format-num-id' => 0,
          'format-pattern' => 'General',
          'format-category' => 'general',
        ),
        'font' => 
        array (
          'font-size' => '11',
          'font-color' => '#202020',
          'font-name' => 'Calibri',
          'font-family' => '2',
          'font-scheme' => 'minor',
        ),
        'fill' => 
        array (
          'fill-pattern' => 'none',
        ),
        'border' => 
        array (
          'border-left-style' => NULL,
          'border-right-style' => NULL,
          'border-top-style' => NULL,
          'border-bottom-style' => NULL,
          'border-diagonal-style' => NULL,
        ),
      ),
      'f' => NULL,
      't' => 'number',
      'o' => '3',
    ),
  ),
  'B' => 
  array (
    1 => 
    array (
      'v' => 'name',
      's' => 
      array (
        'format' => 
        array (
          'format-num-id' => 0,
          'format-pattern' => 'General',
          'format-category' => 'general',
        ),
        'font' => 
        array (
          'font-size' => '11',
          'font-color' => '#202020',
          'font-name' => 'Calibri',
          'font-family' => '2',
          'font-scheme' => 'minor',
          'font-style-bold' => 1,
          'font-charset' => '204',
        ),
        'fill' => 
        array (
          'fill-pattern' => 'none',
        ),
        'border' => 
        array (
          'border-left-style' => NULL,
          'border-right-style' => NULL,
          'border-top-style' => NULL,
          'border-bottom-style' => NULL,
          'border-diagonal-style' => NULL,
        ),
      ),
      'f' => NULL,
      't' => 'string',
      'o' => 'name',
    ),
    2 => 
    array (
      'v' => 'James Bond',
      's' => 
      array (
        'format' => 
        array (
          'format-num-id' => 0,
          'format-pattern' => 'General',
          'format-category' => 'general',
        ),
        'font' => 
        array (
          'font-size' => '11',
          'font-color' => '#202020',
          'font-name' => 'Calibri',
          'font-family' => '2',
          'font-scheme' => 'minor',
        ),
        'fill' => 
        array (
          'fill-pattern' => 'none',
        ),
        'border' => 
        array (
          'border-left-style' => NULL,
          'border-right-style' => NULL,
          'border-top-style' => NULL,
          'border-bottom-style' => NULL,
          'border-diagonal-style' => NULL,
        ),
      ),
      'f' => NULL,
      't' => 'string',
      'o' => 'James Bond',
    ),
    3 => 
    array (
      'v' => 'Ellen Louise Ripley',
      's' => 
      array (
        'format' => 
        array (
          'format-num-id' => 0,
          'format-pattern' => 'General',
          'format-category' => 'general',
        ),
        'font' => 
        array (
          'font-size' => '11',
          'font-color' => '#202020',
          'font-name' => 'Calibri',
          'font-family' => '2',
          'font-scheme' => 'minor',
        ),
        'fill' => 
        array (
          'fill-pattern' => 'none',
        ),
        'border' => 
        array (
          'border-left-style' => NULL,
          'border-right-style' => NULL,
          'border-top-style' => NULL,
          'border-bottom-style' => NULL,
          'border-diagonal-style' => NULL,
        ),
      ),
      'f' => NULL,
      't' => 'string',
      'o' => 'Ellen Louise Ripley',
    ),
    4 => 
    array (
      'v' => 'Captain Jack Sparrow',
      's' => 
      array (
        'format' => 
        array (
          'format-num-id' => 0,
          'format-pattern' => 'General',
          'format-category' => 'general',
        ),
        'font' => 
        array (
          'font-size' => '11',
          'font-color' => '#202020',
          'font-name' => 'Calibri',
          'font-family' => '2',
          'font-scheme' => 'minor',
        ),
        'fill' => 
        array (
          'fill-pattern' => 'none',
        ),
        'border' => 
        array (
          'border-left-style' => NULL,
          'border-right-style' => NULL,
          'border-top-style' => NULL,
          'border-bottom-style' => NULL,
          'border-diagonal-style' => NULL,
        ),
      ),
      'f' => NULL,
      't' => 'string',
      'o' => 'Captain Jack Sparrow',
    ),
  ),
  'C' => 
  array (
    1 => 
    array (
      'v' => 'birthday',
      's' => 
      array (
        'format' => 
        array (
          'format-num-id' => 0,
          'format-pattern' => 'General',
          'format-category' => 'general',
        ),
        'font' => 
        array (
          'font-size' => '11',
          'font-color' => '#202020',
          'font-name' => 'Calibri',
          'font-family' => '2',
          'font-scheme' => 'minor',
          'font-style-bold' => 1,
          'font-charset' => '204',
        ),
        'fill' => 
        array (
          'fill-pattern' => 'none',
        ),
        'border' => 
        array (
          'border-left-style' => NULL,
          'border-right-style' => NULL,
          'border-top-style' => NULL,
          'border-bottom-style' => NULL,
          'border-diagonal-style' => NULL,
        ),
      ),
      'f' => NULL,
      't' => 'string',
      'o' => 'birthday',
    ),
    2 => 
    array (
      'v' => -2205187200,
      's' => 
      array (
        'format' => 
        array (
          'format-num-id' => 14,
          'format-pattern' => 'm/d/yy',
          'format-category' => 'date',
        ),
        'font' => 
        array (
          'font-size' => '11',
          'font-color' => '#202020',
          'font-name' => 'Calibri',
          'font-family' => '2',
          'font-scheme' => 'minor',
        ),
        'fill' => 
        array (
          'fill-pattern' => 'none',
        ),
        'border' => 
        array (
          'border-left-style' => NULL,
          'border-right-style' => NULL,
          'border-top-style' => NULL,
          'border-bottom-style' => NULL,
          'border-diagonal-style' => NULL,
        ),
      ),
      'f' => NULL,
      't' => 'date',
      'o' => '45',
    ),
    3 => 
    array (
      'v' => 6614697600,
      's' => 
      array (
        'format' => 
        array (
          'format-num-id' => 14,
          'format-pattern' => 'm/d/yy',
          'format-category' => 'date',
        ),
        'font' => 
        array (
          'font-size' => '11',
          'font-color' => '#202020',
          'font-name' => 'Calibri',
          'font-family' => '2',
          'font-scheme' => 'minor',
        ),
        'fill' => 
        array (
          'fill-pattern' => 'none',
        ),
        'border' => 
        array (
          'border-left-style' => NULL,
          'border-right-style' => NULL,
          'border-top-style' => NULL,
          'border-bottom-style' => NULL,
          'border-diagonal-style' => NULL,
        ),
      ),
      'f' => NULL,
      't' => 'date',
      'o' => '102128',
    ),
    4 => 
    array (
      'v' => -6845212800,
      's' => 
      array (
        'format' => 
        array (
          'format-num-id' => 14,
          'format-pattern' => 'm/d/yy',
          'format-category' => 'date',
        ),
        'font' => 
        array (
          'font-size' => '11',
          'font-color' => '#202020',
          'font-name' => 'Calibri',
          'font-family' => '2',
          'font-scheme' => 'minor',
        ),
        'fill' => 
        array (
          'fill-pattern' => 'none',
        ),
        'border' => 
        array (
          'border-left-style' => NULL,
          'border-right-style' => NULL,
          'border-top-style' => NULL,
          'border-bottom-style' => NULL,
          'border-diagonal-style' => NULL,
        ),
      ),
      'f' => NULL,
      't' => 'date',
      'o' => '31.01.1753',
    ),
  ),
  'D' => 
  array (
    1 => 
    array (
      'v' => 'random_int',
      's' => 
      array (
        'format' => 
        array (
          'format-num-id' => 0,
          'format-pattern' => 'General',
          'format-category' => 'general',
        ),
        'font' => 
        array (
          'font-size' => '11',
          'font-color' => '#202020',
          'font-name' => 'Calibri',
          'font-family' => '2',
          'font-scheme' => 'minor',
          'font-style-bold' => 1,
          'font-charset' => '204',
        ),
        'fill' => 
        array (
          'fill-pattern' => 'none',
        ),
        'border' => 
        array (
          'border-left-style' => NULL,
          'border-right-style' => NULL,
          'border-top-style' => NULL,
          'border-bottom-style' => NULL,
          'border-diagonal-style' => NULL,
        ),
      ),
      'f' => NULL,
      't' => 'string',
      'o' => 'random_int',
    ),
    2 => 
    array (
      'v' => 4573,
      's' => 
      array (
        'format' => 
        array (
          'format-num-id' => 0,
          'format-pattern' => 'General',
          'format-category' => 'general',
        ),
        'font' => 
        array (
          'font-size' => '11',
          'font-color' => '#202020',
          'font-name' => 'Calibri',
          'font-family' => '2',
          'font-scheme' => 'minor',
        ),
        'fill' => 
        array (
          'fill-pattern' => 'none',
        ),
        'border' => 
        array (
          'border-left-style' => NULL,
          'border-right-style' => NULL,
          'border-top-style' => NULL,
          'border-bottom-style' => NULL,
          'border-diagonal-style' => NULL,
        ),
      ),
      'f' => NULL,
      't' => 'number',
      'o' => '4573',
    ),
    3 => 
    array (
      'v' => 982630,
      's' => 
      array (
        'format' => 
        array (
          'format-num-id' => 0,
          'format-pattern' => 'General',
          'format-category' => 'general',
        ),
        'font' => 
        array (
          'font-size' => '11',
          'font-color' => '#202020',
          'font-name' => 'Calibri',
          'font-family' => '2',
          'font-scheme' => 'minor',
        ),
        'fill' => 
        array (
          'fill-pattern' => 'none',
        ),
        'border' => 
        array (
          'border-left-style' => NULL,
          'border-right-style' => NULL,
          'border-top-style' => NULL,
          'border-bottom-style' => NULL,
          'border-diagonal-style' => NULL,
        ),
      ),
      'f' => NULL,
      't' => 'number',
      'o' => '982630',
    ),
    4 => 
    array (
      'v' => 7239,
      's' => 
      array (
        'format' => 
        array (
          'format-num-id' => 0,
          'format-pattern' => 'General',
          'format-category' => 'general',
        ),
        'font' => 
        array (
          'font-size' => '11',
          'font-color' => '#202020',
          'font-name' => 'Calibri',
          'font-family' => '2',
          'font-scheme' => 'minor',
        ),
        'fill' => 
        array (
          'fill-pattern' => 'none',
        ),
        'border' => 
        array (
          'border-left-style' => NULL,
          'border-right-style' => NULL,
          'border-top-style' => NULL,
          'border-bottom-style' => NULL,
          'border-diagonal-style' => NULL,
        ),
      ),
      'f' => NULL,
      't' => 'number',
      'o' => '7239',
    ),
  ),
);
