<?php

// Snapshot: dates--formatted
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  1 => 
  array (
    'A' => 'full datetime 1',
    'B' => '1983-12-31 05:21:03',
  ),
  2 => 
  array (
    'A' => 'full datetime 2',
    'B' => '1983-12-31 05:21:03',
  ),
  3 => 
  array (
    'A' => 'date 1',
    'B' => '1983-12-31 05:21:03',
  ),
  4 => 
  array (
    'A' => 'date 2',
    'B' => '1983-12-31 05:21:03',
  ),
  5 => 
  array (
    'A' => 'day + month',
    'B' => '1983-12-31 05:21:03',
  ),
  6 => 
  array (
    'A' => 'month + year',
    'B' => '1983-12-31 05:21:03',
  ),
  7 => 
  array (
    'A' => 'time 1',
    'B' => '1983-12-31 05:21:03',
  ),
  8 => 
  array (
    'A' => 'hours + min',
    'B' => '1983-12-31 05:21:03',
  ),
  9 => 
  array (
    'A' => 'min + sec',
    'B' => '1983-12-31 05:21:03',
  ),
);
