<?php

// Snapshot: dates--cells-typed
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  'A1' => 
  array (
    'v' => 'full datetime 1',
    's' => 0,
    'f' => NULL,
    't' => 'string',
    'o' => 'full datetime 1',
  ),
  'B1' => 
  array (
    'v' => 441696063,
    's' => 1,
    'f' => NULL,
    't' => 'date',
    'o' => '30681.222951388889',
  ),
  'A2' => 
  array (
    'v' => 'full datetime 2',
    's' => 0,
    'f' => NULL,
    't' => 'string',
    'o' => 'full datetime 2',
  ),
  'B2' => 
  array (
    'v' => 441696063,
    's' => 2,
    'f' => NULL,
    't' => 'date',
    'o' => '30681.222951388889',
  ),
  'A3' => 
  array (
    'v' => 'date 1',
    's' => 0,
    'f' => NULL,
    't' => 'string',
    'o' => 'date 1',
  ),
  'B3' => 
  array (
    'v' => 441696063,
    's' => 3,
    'f' => NULL,
    't' => 'date',
    'o' => '30681.222951388889',
  ),
  'A4' => 
  array (
    'v' => 'date 2',
    's' => 0,
    'f' => NULL,
    't' => 'string',
    'o' => 'date 2',
  ),
  'B4' => 
  array (
    'v' => 441696063,
    's' => 4,
    'f' => NULL,
    't' => 'date',
    'o' => '30681.222951388889',
  ),
  'A5' => 
  array (
    'v' => 'day + month',
    's' => 0,
    'f' => NULL,
    't' => 'string',
    'o' => 'day + month',
  ),
  'B5' => 
  array (
    'v' => 441696063,
    's' => 5,
    'f' => NULL,
    't' => 'date',
    'o' => '30681.222951388889',
  ),
  'A6' => 
  array (
    'v' => 'month + year',
    's' => 0,
    'f' => NULL,
    't' => 'string',
    'o' => 'month + year',
  ),
  'B6' => 
  array (
    'v' => 441696063,
    's' => 6,
    'f' => NULL,
    't' => 'date',
    'o' => '30681.222951388889',
  ),
  'A7' => 
  array (
    'v' => 'time 1',
    's' => 0,
    'f' => NULL,
    't' => 'string',
    'o' => 'time 1',
  ),
  'B7' => 
  array (
    'v' => 441696063,
    's' => 7,
    'f' => NULL,
    't' => 'date',
    'o' => '30681.222951388889',
  ),
  'A8' => 
  array (
    'v' => 'hours + min',
    's' => 0,
    'f' => NULL,
    't' => 'string',
    'o' => 'hours + min',
  ),
  'B8' => 
  array (
    'v' => 441696063,
    's' => 8,
    'f' => NULL,
    't' => 'date',
    'o' => '30681.222951388889',
  ),
  'A9' => 
  array (
    'v' => 'min + sec',
    's' => 0,
    'f' => NULL,
    't' => 'string',
    'o' => 'min + sec',
  ),
  'B9' => 
  array (
    'v' => 441696063,
    's' => 9,
    'f' => NULL,
    't' => 'date',
    'o' => '30681.222951388889',
  ),
);
