<?php

// Snapshot: dates--formatter-null
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  1 => 
  array (
    'A' => 'full datetime 1',
    'B' => '30681.222951388889',
  ),
  2 => 
  array (
    'A' => 'full datetime 2',
    'B' => '30681.222951388889',
  ),
  3 => 
  array (
    'A' => 'date 1',
    'B' => '30681.222951388889',
  ),
  4 => 
  array (
    'A' => 'date 2',
    'B' => '30681.222951388889',
  ),
  5 => 
  array (
    'A' => 'day + month',
    'B' => '30681.222951388889',
  ),
  6 => 
  array (
    'A' => 'month + year',
    'B' => '30681.222951388889',
  ),
  7 => 
  array (
    'A' => 'time 1',
    'B' => '30681.222951388889',
  ),
  8 => 
  array (
    'A' => 'hours + min',
    'B' => '30681.222951388889',
  ),
  9 => 
  array (
    'A' => 'min + sec',
    'B' => '30681.222951388889',
  ),
);
