<?php

// Snapshot: degenerate--nonstandard-file
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  'sheetNames' => 
  array (
    1 => 'Sheet1',
    2 => 'Filters',
  ),
  'dimension' => '',
  'rows' => 
  array (
  ),
  'cells' => 
  array (
  ),
);
