<?php

// Snapshot: degenerate--single-cell-area
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  2 => 
  array (
    'B' => 'James Bond',
    'C' => -2205187200,
    'D' => 4573,
  ),
  3 => 
  array (
    'B' => 'Ellen Louise Ripley',
    'C' => 6614697600,
    'D' => 982630,
  ),
  4 => 
  array (
    'B' => 'Captain Jack Sparrow',
    'C' => -6845212800,
    'D' => 7239,
  ),
);
