<?php

// Snapshot: degenerate--absolute-path-worksheet
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  1 => 
  array (
    'A' => 'code',
    'B' => 'pairCode',
    'C' => 'price',
  ),
  2 => 
  array (
    'A' => '257109',
    'B' => NULL,
    'C' => '14201',
  ),
  3 => 
  array (
    'A' => '983ST13',
    'B' => NULL,
    'C' => '821',
  ),
  4 => 
  array (
    'A' => '983ST16',
    'B' => NULL,
    'C' => '341352',
  ),
  5 => 
  array (
    'A' => 'ZAUFS00079',
    'B' => NULL,
    'C' => '8573',
  ),
  6 => 
  array (
    'A' => 'MO305',
    'B' => NULL,
    'C' => '8446',
  ),
  7 => 
  array (
    'A' => 'MO307',
    'B' => NULL,
    'C' => '16038',
  ),
  8 => 
  array (
    'A' => 'MO309',
    'B' => NULL,
    'C' => '31099',
  ),
  9 => 
  array (
    'A' => 'MO311',
    'B' => NULL,
    'C' => '76711',
  ),
  10 => 
  array (
    'A' => 'MO313',
    'B' => NULL,
    'C' => '153251',
  ),
  11 => 
  array (
    'A' => 'MO315',
    'B' => NULL,
    'C' => '379108',
  ),
  12 => 
  array (
    'A' => 'MO317',
    'B' => NULL,
    'C' => '757996',
  ),
  13 => 
  array (
    'A' => 'MO319',
    'B' => NULL,
    'C' => '1502587',
  ),
  14 => 
  array (
    'A' => 'AH004',
    'B' => NULL,
    'C' => '3616',
  ),
  15 => 
  array (
    'A' => 'AH007',
    'B' => NULL,
    'C' => '8388',
  ),
  16 => 
  array (
    'A' => 'AH010',
    'B' => NULL,
    'C' => '15775',
  ),
  17 => 
  array (
    'A' => 'AH011',
    'B' => NULL,
    'C' => '30946',
  ),
  18 => 
  array (
    'A' => 'AH012',
    'B' => NULL,
    'C' => '30612',
  ),
  19 => 
  array (
    'A' => 'AH013',
    'B' => NULL,
    'C' => '76500',
  ),
  20 => 
  array (
    'A' => 'AH014',
    'B' => NULL,
    'C' => '76895',
  ),
  21 => 
  array (
    'A' => 'AH016',
    'B' => NULL,
    'C' => '151800',
  ),
  22 => 
  array (
    'A' => 'AH017',
    'B' => NULL,
    'C' => '151820',
  ),
  23 => 
  array (
    'A' => 'AH018',
    'B' => NULL,
    'C' => '152138',
  ),
  24 => 
  array (
    'A' => 'AH019',
    'B' => NULL,
    'C' => '378858',
  ),
  25 => 
  array (
    'A' => 'AH020',
    'B' => NULL,
    'C' => '757446',
  ),
  26 => 
  array (
    'A' => 'AH021',
    'B' => NULL,
    'C' => '1506200',
  ),
  27 => 
  array (
    'A' => 'AH026',
    'B' => NULL,
    'C' => '47881',
  ),
  28 => 
  array (
    'A' => 'AH027',
    'B' => NULL,
    'C' => '48186',
  ),
  29 => 
  array (
    'A' => 'VAL001',
    'B' => NULL,
    'C' => '1786',
  ),
  30 => 
  array (
    'A' => 'VAL002',
    'B' => NULL,
    'C' => '4205',
  ),
  31 => 
  array (
    'A' => 'VAL003',
    'B' => NULL,
    'C' => '8229',
  ),
  32 => 
  array (
    'A' => 'VAL004',
    'B' => NULL,
    'C' => '9085',
  ),
  33 => 
  array (
    'A' => 'VAL005',
    'B' => NULL,
    'C' => '9229',
  ),
  34 => 
  array (
    'A' => 'VAL006',
    'B' => NULL,
    'C' => '15893',
  ),
  35 => 
  array (
    'A' => 'VAL007',
    'B' => NULL,
    'C' => '18457',
  ),
  36 => 
  array (
    'A' => 'VAL008',
    'B' => NULL,
    'C' => '31507',
  ),
  37 => 
  array (
    'A' => 'VAL009',
    'B' => NULL,
    'C' => '33277',
  ),
  38 => 
  array (
    'A' => 'VAL010',
    'B' => NULL,
    'C' => '48384',
  ),
  39 => 
  array (
    'A' => 'VAL011',
    'B' => NULL,
    'C' => '77642',
  ),
  40 => 
  array (
    'A' => 'VAL012',
    'B' => NULL,
    'C' => '153321',
  ),
  41 => 
  array (
    'A' => 'VAL013',
    'B' => NULL,
    'C' => '379348',
  ),
  42 => 
  array (
    'A' => 'VAL014',
    'B' => NULL,
    'C' => '758366',
  ),
  43 => 
  array (
    'A' => 'VAL015',
    'B' => NULL,
    'C' => '1501676',
  ),
  44 => 
  array (
    'A' => 'VAL016',
    'B' => NULL,
    'C' => '50723',
  ),
  45 => 
  array (
    'A' => 'VAL017',
    'B' => NULL,
    'C' => '79422',
  ),
  46 => 
  array (
    'A' => 'VAL018',
    'B' => NULL,
    'C' => '156421',
  ),
  47 => 
  array (
    'A' => '983ST27',
    'B' => NULL,
    'C' => '783',
  ),
  48 => 
  array (
    'A' => '983ST28',
    'B' => NULL,
    'C' => '860',
  ),
  49 => 
  array (
    'A' => '983ST36',
    'B' => NULL,
    'C' => '69911',
  ),
  50 => 
  array (
    'A' => '22611',
    'B' => NULL,
    'C' => '50268',
  ),
  51 => 
  array (
    'A' => '847',
    'B' => NULL,
    'C' => '48923',
  ),
  52 => 
  array (
    'A' => '3419',
    'B' => NULL,
    'C' => '5818',
  ),
  53 => 
  array (
    'A' => '983ST19',
    'B' => NULL,
    'C' => '730',
  ),
  54 => 
  array (
    'A' => '983ST25',
    'B' => NULL,
    'C' => '20135',
  ),
  55 => 
  array (
    'A' => '983ST29',
    'B' => NULL,
    'C' => '866',
  ),
  56 => 
  array (
    'A' => '279765',
    'B' => NULL,
    'C' => '47802',
  ),
  57 => 
  array (
    'A' => '983ST169',
    'B' => NULL,
    'C' => '20135',
  ),
  58 => 
  array (
    'A' => '315377',
    'B' => NULL,
    'C' => '48474',
  ),
  59 => 
  array (
    'A' => '315380',
    'B' => NULL,
    'C' => '50716',
  ),
  60 => 
  array (
    'A' => '315383',
    'B' => NULL,
    'C' => '48699',
  ),
  61 => 
  array (
    'A' => '315611',
    'B' => NULL,
    'C' => '24937',
  ),
  62 => 
  array (
    'A' => '315614',
    'B' => NULL,
    'C' => '12943',
  ),
  63 => 
  array (
    'A' => 'ZAUFS00067',
    'B' => NULL,
    'C' => '1965',
  ),
  64 => 
  array (
    'A' => 'ZAUFS00074',
    'B' => NULL,
    'C' => '4637',
  ),
  65 => 
  array (
    'A' => 'MO301',
    'B' => NULL,
    'C' => '1898',
  ),
  66 => 
  array (
    'A' => 'MO303',
    'B' => NULL,
    'C' => '3490',
  ),
  67 => 
  array (
    'A' => 'AH001',
    'B' => NULL,
    'C' => '1854',
  ),
  68 => 
  array (
    'A' => 'AH002',
    'B' => NULL,
    'C' => '1914',
  ),
  69 => 
  array (
    'A' => 'AH003',
    'B' => NULL,
    'C' => '3498',
  ),
  70 => 
  array (
    'A' => 'AH006',
    'B' => NULL,
    'C' => '8328',
  ),
  71 => 
  array (
    'A' => 'AH009',
    'B' => NULL,
    'C' => '15683',
  ),
);
