<?php

// Snapshot: degenerate--empty-rows
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  1 => 
  array (
    'A' => NULL,
    'B' => '',
    'C' => '',
    'D' => 0,
  ),
);
