<?php

// Snapshot: degenerate--wrong-dimension-rows
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  3 => 
  array (
    'C' => 'q',
    'D' => 'w',
    'E' => 'e',
  ),
  4 => 
  array (
    'C' => 'a',
    'D' => 's',
    'E' => 'd',
  ),
  5 => 
  array (
    'C' => 'z',
    'D' => 'x',
    'E' => 'c',
  ),
);
