<?php

// Snapshot: degenerate--wrong-dimension-cells
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  'C3' => 'q',
  'D3' => 'w',
  'E3' => 'e',
  'C4' => 'a',
  'D4' => 's',
  'E4' => 'd',
  'C5' => 'z',
  'D5' => 'x',
  'E5' => 'c',
);
