<?php

// Snapshot: first-row--with-styles
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  'A' => 
  array (
    'v' => '#',
    's' => 
    array (
      'format' => 
      array (
        'format-num-id' => 0,
        'format-pattern' => 'General',
        'format-category' => 'general',
      ),
      'font' => 
      array (
        'font-size' => '11',
        'font-color' => '#202020',
        'font-name' => 'Calibri',
        'font-family' => '2',
        'font-scheme' => 'minor',
        'font-style-bold' => 1,
        'font-charset' => '204',
      ),
      'fill' => 
      array (
        'fill-pattern' => 'none',
      ),
      'border' => 
      array (
        'border-left-style' => NULL,
        'border-right-style' => NULL,
        'border-top-style' => NULL,
        'border-bottom-style' => NULL,
        'border-diagonal-style' => NULL,
      ),
    ),
    'f' => NULL,
    't' => 'string',
    'o' => '#',
  ),
  'B' => 
  array (
    'v' => 'name',
    's' => 
    array (
      'format' => 
      array (
        'format-num-id' => 0,
        'format-pattern' => 'General',
        'format-category' => 'general',
      ),
      'font' => 
      array (
        'font-size' => '11',
        'font-color' => '#202020',
        'font-name' => 'Calibri',
        'font-family' => '2',
        'font-scheme' => 'minor',
        'font-style-bold' => 1,
        'font-charset' => '204',
      ),
      'fill' => 
      array (
        'fill-pattern' => 'none',
      ),
      'border' => 
      array (
        'border-left-style' => NULL,
        'border-right-style' => NULL,
        'border-top-style' => NULL,
        'border-bottom-style' => NULL,
        'border-diagonal-style' => NULL,
      ),
    ),
    'f' => NULL,
    't' => 'string',
    'o' => 'name',
  ),
  'C' => 
  array (
    'v' => 'birthday',
    's' => 
    array (
      'format' => 
      array (
        'format-num-id' => 0,
        'format-pattern' => 'General',
        'format-category' => 'general',
      ),
      'font' => 
      array (
        'font-size' => '11',
        'font-color' => '#202020',
        'font-name' => 'Calibri',
        'font-family' => '2',
        'font-scheme' => 'minor',
        'font-style-bold' => 1,
        'font-charset' => '204',
      ),
      'fill' => 
      array (
        'fill-pattern' => 'none',
      ),
      'border' => 
      array (
        'border-left-style' => NULL,
        'border-right-style' => NULL,
        'border-top-style' => NULL,
        'border-bottom-style' => NULL,
        'border-diagonal-style' => NULL,
      ),
    ),
    'f' => NULL,
    't' => 'string',
    'o' => 'birthday',
  ),
  'D' => 
  array (
    'v' => 'random_int',
    's' => 
    array (
      'format' => 
      array (
        'format-num-id' => 0,
        'format-pattern' => 'General',
        'format-category' => 'general',
      ),
      'font' => 
      array (
        'font-size' => '11',
        'font-color' => '#202020',
        'font-name' => 'Calibri',
        'font-family' => '2',
        'font-scheme' => 'minor',
        'font-style-bold' => 1,
        'font-charset' => '204',
      ),
      'fill' => 
      array (
        'fill-pattern' => 'none',
      ),
      'border' => 
      array (
        'border-left-style' => NULL,
        'border-right-style' => NULL,
        'border-top-style' => NULL,
        'border-bottom-style' => NULL,
        'border-diagonal-style' => NULL,
      ),
    ),
    'f' => NULL,
    't' => 'string',
    'o' => 'random_int',
  ),
);
