<?php

// Snapshot: keys-offset--rows-col-zero-based
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  2 => 
  array (
    0 => 'Data of Sheet1',
    1 => NULL,
    2 => NULL,
  ),
  4 => 
  array (
    0 => 'Name',
    1 => 'Date',
    2 => 'Color',
  ),
  5 => 
  array (
    0 => 'Giovanni',
    1 => 18316800,
    2 => 'Red',
  ),
  6 => 
  array (
    0 => 'James',
    1 => -777600,
    2 => 'Green',
  ),
  7 => 
  array (
    0 => 'Mateusz',
    1 => -62121600,
    2 => 'Blue',
  ),
  8 => 
  array (
    0 => 'Francesco',
    1 => 38707200,
    2 => 'Brown',
  ),
  9 => 
  array (
    0 => 'Miguel',
    1 => 102729600,
    2 => 'Yellow',
  ),
  10 => 
  array (
    0 => 'Pedro',
    1 => -75859200,
    2 => 'Orange',
  ),
  11 => 
  array (
    0 => 'Evan',
    1 => -132969600,
    2 => 'Purple',
  ),
);
