<?php

// Snapshot: keys-offset--rows-first-row-swap
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  'Data of Sheet1' => 
  array (
    4 => 'Name',
    5 => 'Giovanni',
    6 => 'James',
    7 => 'Mateusz',
    8 => 'Francesco',
    9 => 'Miguel',
    10 => 'Pedro',
    11 => 'Evan',
  ),
  'C' => 
  array (
    4 => 'Date',
    5 => 18316800,
    6 => -777600,
    7 => -62121600,
    8 => 38707200,
    9 => 102729600,
    10 => -75859200,
    11 => -132969600,
  ),
  'D' => 
  array (
    4 => 'Color',
    5 => 'Red',
    6 => 'Green',
    7 => 'Blue',
    8 => 'Brown',
    9 => 'Yellow',
    10 => 'Orange',
    11 => 'Purple',
  ),
);
