<?php

// Snapshot: keys-origin--rows-col-zero-based
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  1 => 
  array (
    0 => '#',
    1 => 'name',
    2 => 'birthday',
    3 => 'random_int',
  ),
  2 => 
  array (
    0 => 1,
    1 => 'James Bond',
    2 => -2205187200,
    3 => 4573,
  ),
  3 => 
  array (
    0 => 2,
    1 => 'Ellen Louise Ripley',
    2 => 6614697600,
    3 => 982630,
  ),
  4 => 
  array (
    0 => 3,
    1 => 'Captain Jack Sparrow',
    2 => -6845212800,
    3 => 7239,
  ),
);
