<?php

// Snapshot: keys-origin--rows-swap
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  'A' => 
  array (
    1 => '#',
    2 => 1,
    3 => 2,
    4 => 3,
  ),
  'B' => 
  array (
    1 => 'name',
    2 => 'James Bond',
    3 => 'Ellen Louise Ripley',
    4 => 'Captain Jack Sparrow',
  ),
  'C' => 
  array (
    1 => 'birthday',
    2 => -2205187200,
    3 => 6614697600,
    4 => -6845212800,
  ),
  'D' => 
  array (
    1 => 'random_int',
    2 => 4573,
    3 => 982630,
    4 => 7239,
  ),
);
