<?php

// Snapshot: keys-offset--rows-col-one-based
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  2 => 
  array (
    1 => 'Data of Sheet1',
    2 => NULL,
    3 => NULL,
  ),
  4 => 
  array (
    1 => 'Name',
    2 => 'Date',
    3 => 'Color',
  ),
  5 => 
  array (
    1 => 'Giovanni',
    2 => 18316800,
    3 => 'Red',
  ),
  6 => 
  array (
    1 => 'James',
    2 => -777600,
    3 => 'Green',
  ),
  7 => 
  array (
    1 => 'Mateusz',
    2 => -62121600,
    3 => 'Blue',
  ),
  8 => 
  array (
    1 => 'Francesco',
    2 => 38707200,
    3 => 'Brown',
  ),
  9 => 
  array (
    1 => 'Miguel',
    2 => 102729600,
    3 => 'Yellow',
  ),
  10 => 
  array (
    1 => 'Pedro',
    2 => -75859200,
    3 => 'Orange',
  ),
  11 => 
  array (
    1 => 'Evan',
    2 => -132969600,
    3 => 'Purple',
  ),
);
