<?php

// Snapshot: keys-offset--rows-first-row
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  4 => 
  array (
    'Data of Sheet1' => 'Name',
    'C' => 'Date',
    'D' => 'Color',
  ),
  5 => 
  array (
    'Data of Sheet1' => 'Giovanni',
    'C' => 18316800,
    'D' => 'Red',
  ),
  6 => 
  array (
    'Data of Sheet1' => 'James',
    'C' => -777600,
    'D' => 'Green',
  ),
  7 => 
  array (
    'Data of Sheet1' => 'Mateusz',
    'C' => -62121600,
    'D' => 'Blue',
  ),
  8 => 
  array (
    'Data of Sheet1' => 'Francesco',
    'C' => 38707200,
    'D' => 'Brown',
  ),
  9 => 
  array (
    'Data of Sheet1' => 'Miguel',
    'C' => 102729600,
    'D' => 'Yellow',
  ),
  10 => 
  array (
    'Data of Sheet1' => 'Pedro',
    'C' => -75859200,
    'D' => 'Orange',
  ),
  11 => 
  array (
    'Data of Sheet1' => 'Evan',
    'C' => -132969600,
    'D' => 'Purple',
  ),
);
