<?php

// Snapshot: keys-origin--rows-one-based
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  1 => 
  array (
    1 => '#',
    2 => 'name',
    3 => 'birthday',
    4 => 'random_int',
  ),
  2 => 
  array (
    1 => 1,
    2 => 'James Bond',
    3 => -2205187200,
    4 => 4573,
  ),
  3 => 
  array (
    1 => 2,
    2 => 'Ellen Louise Ripley',
    3 => 6614697600,
    4 => 982630,
  ),
  4 => 
  array (
    1 => 3,
    2 => 'Captain Jack Sparrow',
    3 => -6845212800,
    4 => 7239,
  ),
);
