<?php

// Snapshot: keys-origin--rows-first-row-swap
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  '#' => 
  array (
    2 => 1,
    3 => 2,
    4 => 3,
  ),
  'name' => 
  array (
    2 => 'James Bond',
    3 => 'Ellen Louise Ripley',
    4 => 'Captain Jack Sparrow',
  ),
  'birthday' => 
  array (
    2 => -2205187200,
    3 => 6614697600,
    4 => -6845212800,
  ),
  'random_int' => 
  array (
    2 => 4573,
    3 => 982630,
    4 => 7239,
  ),
);
