<?php

// Snapshot: keys-origin--rows-first-row-row-zero-based
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  0 => 
  array (
    '#' => 1,
    'name' => 'James Bond',
    'birthday' => -2205187200,
    'random_int' => 4573,
  ),
  1 => 
  array (
    '#' => 2,
    'name' => 'Ellen Louise Ripley',
    'birthday' => 6614697600,
    'random_int' => 982630,
  ),
  2 => 
  array (
    '#' => 3,
    'name' => 'Captain Jack Sparrow',
    'birthday' => -6845212800,
    'random_int' => 7239,
  ),
);
