<?php

// Snapshot: keys-origin--rows-original
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  1 => 
  array (
    'A' => '#',
    'B' => 'name',
    'C' => 'birthday',
    'D' => 'random_int',
  ),
  2 => 
  array (
    'A' => 1,
    'B' => 'James Bond',
    'C' => -2205187200,
    'D' => 4573,
  ),
  3 => 
  array (
    'A' => 2,
    'B' => 'Ellen Louise Ripley',
    'C' => 6614697600,
    'D' => 982630,
  ),
  4 => 
  array (
    'A' => 3,
    'B' => 'Captain Jack Sparrow',
    'C' => -6845212800,
    'D' => 7239,
  ),
);
