<?php

// Snapshot: meta--demo-04-styles
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  'sheetNames' => 
  array (
    1 => 'Demo',
  ),
  'countSheets' => 1,
  'visibleSheets' => 
  array (
    0 => 1,
  ),
  'hiddenSheets' => 
  array (
  ),
  'definedNames' => 
  array (
  ),
  'sheetExistsHit' => false,
  'sheetExistsMiss' => false,
  'sheets' => 
  array (
    1 => 
    array (
      'id' => '1',
      'name' => 'Demo',
      'path' => 'xl/worksheets/sheet1.xml',
      'state' => '',
      'isVisible' => true,
      'isHidden' => false,
      'dimension' => 'A1:K107',
      'dimensionArray' => 
      array (
        'min_col_letter' => 'A',
        'min_col_num' => 1,
        'min_row_num' => 1,
        'min_col_abs' => '',
        'min_row_abs' => '',
        'min_cell' => 'A1',
        'min_cell_abs' => 'A1',
        'max_col_letter' => 'K',
        'max_col_num' => 11,
        'max_row_num' => 107,
        'max_col_abs' => '',
        'max_row_abs' => '',
        'max_cell' => 'K107',
        'max_cell_abs' => 'K107',
        'range' => 'A1:K107',
        'range_abs' => 'A1:K107',
      ),
      'countRows' => 107,
      'countCols' => 11,
      'countColumns' => 11,
      'minRow' => 1,
      'maxRow' => 107,
      'minColumn' => 'A',
      'maxColumn' => 'K',
      'firstRow' => 1,
      'firstCol' => 'A',
      'mergedCells' => 
      array (
        'A2' => 'A2:K2',
        'E3' => 'E3:I3',
        'A6' => 'A6:A7',
        'B6' => 'B6:C6',
        'D6' => 'D6:D7',
        'E6' => 'E6:E7',
        'F6' => 'F6:F7',
        'G6' => 'G6:G7',
        'H6' => 'H6:H7',
        'I6' => 'I6:I7',
        'J6' => 'J6:J7',
        'K6' => 'K6:K7',
      ),
    ),
  ),
);
