<?php

// Snapshot: meta--merged-lookup
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  'B2' => 
  array (
    'isMerged' => true,
    'mergedRange' => 'B2:D2',
  ),
  'C3' => 
  array (
    'isMerged' => false,
    'mergedRange' => NULL,
  ),
  'B4' => 
  array (
    'isMerged' => false,
    'mergedRange' => NULL,
  ),
  'D11' => 
  array (
    'isMerged' => false,
    'mergedRange' => NULL,
  ),
  'A1' => 
  array (
    'isMerged' => false,
    'mergedRange' => NULL,
  ),
);
