<?php

// Snapshot: meta--actual-dimension
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  'dimension' => 'D4',
  'actualDimension' => 'C3:E5',
  'countActualRows' => 3,
  'countActualColumns' => 3,
  'minActualRow' => 3,
  'maxActualRow' => 5,
  'minActualColumn' => 'C',
  'maxActualColumn' => 'E',
  'stat' => 
  array (
    'rows' => 
    array (
      'min' => 3,
      'max' => 5,
      'count' => 3,
    ),
    'cols' => 
    array (
      'min' => 'C',
      'max' => 'E',
      'count' => 3,
    ),
    'cells' => 
    array (
      'total' => 9,
      'filled' => 9,
    ),
  ),
);
