<?php

// Snapshot: meta--demo-07-size-freeze-tabs
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  'sheetNames' => 
  array (
    10 => 'report',
    26 => 'EXCEL2.RU (2)',
    18 => 'Лист7',
  ),
  'countSheets' => 3,
  'visibleSheets' => 
  array (
    0 => 10,
  ),
  'hiddenSheets' => 
  array (
    0 => 26,
    1 => 18,
  ),
  'definedNames' => 
  array (
    'anscount' => '2',
    'limcount' => '2',
    'sencount' => '4',
  ),
  'sheetExistsHit' => false,
  'sheetExistsMiss' => false,
  'sheets' => 
  array (
    10 => 
    array (
      'id' => '10',
      'name' => 'report',
      'path' => 'xl/worksheets/sheet1.xml',
      'state' => '',
      'isVisible' => true,
      'isHidden' => false,
      'dimension' => 'A1:H527',
      'dimensionArray' => 
      array (
        'min_col_letter' => 'A',
        'min_col_num' => 1,
        'min_row_num' => 1,
        'min_col_abs' => '',
        'min_row_abs' => '',
        'min_cell' => 'A1',
        'min_cell_abs' => 'A1',
        'max_col_letter' => 'H',
        'max_col_num' => 8,
        'max_row_num' => 527,
        'max_col_abs' => '',
        'max_row_abs' => '',
        'max_cell' => 'H527',
        'max_cell_abs' => 'H527',
        'range' => 'A1:H527',
        'range_abs' => 'A1:H527',
      ),
      'countRows' => 527,
      'countCols' => 8,
      'countColumns' => 8,
      'minRow' => 1,
      'maxRow' => 527,
      'minColumn' => 'A',
      'maxColumn' => 'H',
      'firstRow' => 1,
      'firstCol' => 'A',
      'mergedCells' => 
      array (
      ),
    ),
    26 => 
    array (
      'id' => '26',
      'name' => 'EXCEL2.RU (2)',
      'path' => 'xl/worksheets/sheet2.xml',
      'state' => 'veryHidden',
      'isVisible' => false,
      'isHidden' => true,
      'dimension' => 'A1:G4',
      'dimensionArray' => 
      array (
        'min_col_letter' => 'A',
        'min_col_num' => 1,
        'min_row_num' => 1,
        'min_col_abs' => '',
        'min_row_abs' => '',
        'min_cell' => 'A1',
        'min_cell_abs' => 'A1',
        'max_col_letter' => 'G',
        'max_col_num' => 7,
        'max_row_num' => 4,
        'max_col_abs' => '',
        'max_row_abs' => '',
        'max_cell' => 'G4',
        'max_cell_abs' => 'G4',
        'range' => 'A1:G4',
        'range_abs' => 'A1:G4',
      ),
      'countRows' => 4,
      'countCols' => 7,
      'countColumns' => 7,
      'minRow' => 1,
      'maxRow' => 4,
      'minColumn' => 'A',
      'maxColumn' => 'G',
      'firstRow' => 1,
      'firstCol' => 'A',
      'mergedCells' => 
      array (
        'A1' => 'A1:G1',
      ),
    ),
    18 => 
    array (
      'id' => '18',
      'name' => 'Лист7',
      'path' => 'xl/worksheets/sheet3.xml',
      'state' => 'hidden',
      'isVisible' => false,
      'isHidden' => true,
      'dimension' => 'A1:D9',
      'dimensionArray' => 
      array (
        'min_col_letter' => 'A',
        'min_col_num' => 1,
        'min_row_num' => 1,
        'min_col_abs' => '',
        'min_row_abs' => '',
        'min_cell' => 'A1',
        'min_cell_abs' => 'A1',
        'max_col_letter' => 'D',
        'max_col_num' => 4,
        'max_row_num' => 9,
        'max_col_abs' => '',
        'max_row_abs' => '',
        'max_cell' => 'D9',
        'max_cell_abs' => 'D9',
        'range' => 'A1:D9',
        'range_abs' => 'A1:D9',
      ),
      'countRows' => 9,
      'countCols' => 4,
      'countColumns' => 4,
      'minRow' => 1,
      'maxRow' => 9,
      'minColumn' => 'A',
      'maxColumn' => 'D',
      'firstRow' => 1,
      'firstCol' => 'A',
      'mergedCells' => 
      array (
        'A1' => 'A1:C1',
        'B3' => 'B3:D3',
        'A4' => 'A4:A9',
        'B4' => 'B4:D9',
      ),
    ),
  ),
);
