<?php

// Snapshot: meta--demo-00-test
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  'sheetNames' => 
  array (
    1 => 'Sheet1',
    2 => 'Sheet2',
    3 => 'Sheet3',
  ),
  'countSheets' => 3,
  'visibleSheets' => 
  array (
    0 => 1,
    1 => 2,
    2 => 3,
  ),
  'hiddenSheets' => 
  array (
  ),
  'definedNames' => 
  array (
  ),
  'sheetExistsHit' => false,
  'sheetExistsMiss' => false,
  'sheets' => 
  array (
    1 => 
    array (
      'id' => '1',
      'name' => 'Sheet1',
      'path' => 'xl/worksheets/sheet1.xml',
      'state' => '',
      'isVisible' => true,
      'isHidden' => false,
      'dimension' => 'A1:D4',
      'dimensionArray' => 
      array (
        'min_col_letter' => 'A',
        'min_col_num' => 1,
        'min_row_num' => 1,
        'min_col_abs' => '',
        'min_row_abs' => '',
        'min_cell' => 'A1',
        'min_cell_abs' => 'A1',
        'max_col_letter' => 'D',
        'max_col_num' => 4,
        'max_row_num' => 4,
        'max_col_abs' => '',
        'max_row_abs' => '',
        'max_cell' => 'D4',
        'max_cell_abs' => 'D4',
        'range' => 'A1:D4',
        'range_abs' => 'A1:D4',
      ),
      'countRows' => 4,
      'countCols' => 4,
      'countColumns' => 4,
      'minRow' => 1,
      'maxRow' => 4,
      'minColumn' => 'A',
      'maxColumn' => 'D',
      'firstRow' => 1,
      'firstCol' => 'A',
      'mergedCells' => 
      array (
      ),
    ),
    2 => 
    array (
      'id' => '2',
      'name' => 'Sheet2',
      'path' => 'xl/worksheets/sheet2.xml',
      'state' => '',
      'isVisible' => true,
      'isHidden' => false,
      'dimension' => 'A1:B11',
      'dimensionArray' => 
      array (
        'min_col_letter' => 'A',
        'min_col_num' => 1,
        'min_row_num' => 1,
        'min_col_abs' => '',
        'min_row_abs' => '',
        'min_cell' => 'A1',
        'min_cell_abs' => 'A1',
        'max_col_letter' => 'B',
        'max_col_num' => 2,
        'max_row_num' => 11,
        'max_col_abs' => '',
        'max_row_abs' => '',
        'max_cell' => 'B11',
        'max_cell_abs' => 'B11',
        'range' => 'A1:B11',
        'range_abs' => 'A1:B11',
      ),
      'countRows' => 11,
      'countCols' => 2,
      'countColumns' => 2,
      'minRow' => 1,
      'maxRow' => 11,
      'minColumn' => 'A',
      'maxColumn' => 'B',
      'firstRow' => 1,
      'firstCol' => 'A',
      'mergedCells' => 
      array (
      ),
    ),
    3 => 
    array (
      'id' => '3',
      'name' => 'Sheet3',
      'path' => 'xl/worksheets/sheet3.xml',
      'state' => '',
      'isVisible' => true,
      'isHidden' => false,
      'dimension' => 'A1:A7',
      'dimensionArray' => 
      array (
        'min_col_letter' => 'A',
        'min_col_num' => 1,
        'min_row_num' => 1,
        'min_col_abs' => '',
        'min_row_abs' => '',
        'min_cell' => 'A1',
        'min_cell_abs' => 'A1',
        'max_col_letter' => 'A',
        'max_col_num' => 1,
        'max_row_num' => 7,
        'max_col_abs' => '',
        'max_row_abs' => '',
        'max_cell' => 'A7',
        'max_cell_abs' => 'A7',
        'range' => 'A1:A7',
        'range_abs' => 'A1:A7',
      ),
      'countRows' => 7,
      'countCols' => 1,
      'countColumns' => 1,
      'minRow' => 1,
      'maxRow' => 7,
      'minColumn' => 'A',
      'maxColumn' => 'A',
      'firstRow' => 1,
      'firstCol' => 'A',
      'mergedCells' => 
      array (
      ),
    ),
  ),
);
