<?php

// Snapshot: meta--demo-02-advanced
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  'sheetNames' => 
  array (
    2 => 'Demo1',
    1 => 'Demo2',
    3 => 'Demo3',
  ),
  'countSheets' => 3,
  'visibleSheets' => 
  array (
    0 => 2,
    1 => 1,
    2 => 3,
  ),
  'hiddenSheets' => 
  array (
  ),
  'definedNames' => 
  array (
    'Headers' => 'Demo1!$B$4:$D$4',
    'Values' => 'Demo1!$B$5:$D$11',
  ),
  'sheetExistsHit' => false,
  'sheetExistsMiss' => false,
  'sheets' => 
  array (
    2 => 
    array (
      'id' => '2',
      'name' => 'Demo1',
      'path' => 'xl/worksheets/sheet1.xml',
      'state' => '',
      'isVisible' => true,
      'isHidden' => false,
      'dimension' => 'B2:D11',
      'dimensionArray' => 
      array (
        'min_col_letter' => 'B',
        'min_col_num' => 2,
        'min_row_num' => 2,
        'min_col_abs' => '',
        'min_row_abs' => '',
        'min_cell' => 'B2',
        'min_cell_abs' => 'B2',
        'max_col_letter' => 'D',
        'max_col_num' => 4,
        'max_row_num' => 11,
        'max_col_abs' => '',
        'max_row_abs' => '',
        'max_cell' => 'D11',
        'max_cell_abs' => 'D11',
        'range' => 'B2:D11',
        'range_abs' => 'B2:D11',
      ),
      'countRows' => 10,
      'countCols' => 3,
      'countColumns' => 3,
      'minRow' => 2,
      'maxRow' => 11,
      'minColumn' => 'B',
      'maxColumn' => 'D',
      'firstRow' => 2,
      'firstCol' => 'B',
      'mergedCells' => 
      array (
        'B2' => 'B2:D2',
      ),
    ),
    1 => 
    array (
      'id' => '1',
      'name' => 'Demo2',
      'path' => 'xl/worksheets/sheet2.xml',
      'state' => '',
      'isVisible' => true,
      'isHidden' => false,
      'dimension' => 'B2:H13',
      'dimensionArray' => 
      array (
        'min_col_letter' => 'B',
        'min_col_num' => 2,
        'min_row_num' => 2,
        'min_col_abs' => '',
        'min_row_abs' => '',
        'min_cell' => 'B2',
        'min_cell_abs' => 'B2',
        'max_col_letter' => 'H',
        'max_col_num' => 8,
        'max_row_num' => 13,
        'max_col_abs' => '',
        'max_row_abs' => '',
        'max_cell' => 'H13',
        'max_cell_abs' => 'H13',
        'range' => 'B2:H13',
        'range_abs' => 'B2:H13',
      ),
      'countRows' => 12,
      'countCols' => 7,
      'countColumns' => 7,
      'minRow' => 2,
      'maxRow' => 13,
      'minColumn' => 'B',
      'maxColumn' => 'H',
      'firstRow' => 2,
      'firstCol' => 'B',
      'mergedCells' => 
      array (
        'B2' => 'B2:D2',
        'F2' => 'F2:H2',
      ),
    ),
    3 => 
    array (
      'id' => '3',
      'name' => 'Demo3',
      'path' => 'xl/worksheets/sheet3.xml',
      'state' => '',
      'isVisible' => true,
      'isHidden' => false,
      'dimension' => 'A2:D6',
      'dimensionArray' => 
      array (
        'min_col_letter' => 'A',
        'min_col_num' => 1,
        'min_row_num' => 2,
        'min_col_abs' => '',
        'min_row_abs' => '',
        'min_cell' => 'A2',
        'min_cell_abs' => 'A2',
        'max_col_letter' => 'D',
        'max_col_num' => 4,
        'max_row_num' => 6,
        'max_col_abs' => '',
        'max_row_abs' => '',
        'max_cell' => 'D6',
        'max_cell_abs' => 'D6',
        'range' => 'A2:D6',
        'range_abs' => 'A2:D6',
      ),
      'countRows' => 5,
      'countCols' => 4,
      'countColumns' => 4,
      'minRow' => 2,
      'maxRow' => 6,
      'minColumn' => 'A',
      'maxColumn' => 'D',
      'firstRow' => 2,
      'firstCol' => 'A',
      'mergedCells' => 
      array (
      ),
    ),
  ),
);
