<?php

// Snapshot: rows--style-idx
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  1 => 
  array (
    'A' => 
    array (
      'v' => '#',
      's' => 2,
      'f' => NULL,
      't' => 'string',
      'o' => '#',
    ),
    'B' => 
    array (
      'v' => 'name',
      's' => 2,
      'f' => NULL,
      't' => 'string',
      'o' => 'name',
    ),
    'C' => 
    array (
      'v' => 'birthday',
      's' => 2,
      'f' => NULL,
      't' => 'string',
      'o' => 'birthday',
    ),
    'D' => 
    array (
      'v' => 'random_int',
      's' => 2,
      'f' => NULL,
      't' => 'string',
      'o' => 'random_int',
    ),
  ),
  2 => 
  array (
    'A' => 
    array (
      'v' => 1,
      's' => 0,
      'f' => NULL,
      't' => 'number',
      'o' => '1',
    ),
    'B' => 
    array (
      'v' => 'James Bond',
      's' => 0,
      'f' => NULL,
      't' => 'string',
      'o' => 'James Bond',
    ),
    'C' => 
    array (
      'v' => -2205187200,
      's' => 1,
      'f' => NULL,
      't' => 'date',
      'o' => '45',
    ),
    'D' => 
    array (
      'v' => 4573,
      's' => 0,
      'f' => NULL,
      't' => 'number',
      'o' => '4573',
    ),
  ),
  3 => 
  array (
    'A' => 
    array (
      'v' => 2,
      's' => 0,
      'f' => NULL,
      't' => 'number',
      'o' => '2',
    ),
    'B' => 
    array (
      'v' => 'Ellen Louise Ripley',
      's' => 0,
      'f' => NULL,
      't' => 'string',
      'o' => 'Ellen Louise Ripley',
    ),
    'C' => 
    array (
      'v' => 6614697600,
      's' => 1,
      'f' => NULL,
      't' => 'date',
      'o' => '102128',
    ),
    'D' => 
    array (
      'v' => 982630,
      's' => 0,
      'f' => NULL,
      't' => 'number',
      'o' => '982630',
    ),
  ),
  4 => 
  array (
    'A' => 
    array (
      'v' => 3,
      's' => 0,
      'f' => NULL,
      't' => 'number',
      'o' => '3',
    ),
    'B' => 
    array (
      'v' => 'Captain Jack Sparrow',
      's' => 0,
      'f' => NULL,
      't' => 'string',
      'o' => 'Captain Jack Sparrow',
    ),
    'C' => 
    array (
      'v' => -6845212800,
      's' => 1,
      'f' => NULL,
      't' => 'date',
      'o' => '31.01.1753',
    ),
    'D' => 
    array (
      'v' => 7239,
      's' => 0,
      'f' => NULL,
      't' => 'number',
      'o' => '7239',
    ),
  ),
);
