<?php

// Snapshot: rows--with-styles-from
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  2 => 
  array (
    'B' => 
    array (
      'v' => 'Data of Sheet1',
      's' => 
      array (
        'format' => 
        array (
          'format-num-id' => 0,
          'format-pattern' => 'General',
          'format-category' => 'general',
          'format-align-horizontal' => 'center',
        ),
        'font' => 
        array (
          'font-size' => '12',
          'font-color' => '#202020',
          'font-name' => 'Calibri',
          'font-family' => '2',
          'font-scheme' => 'minor',
          'font-style-bold' => 1,
          'font-charset' => '204',
        ),
        'fill' => 
        array (
          'fill-pattern' => 'none',
        ),
        'border' => 
        array (
          'border-left-style' => NULL,
          'border-right-style' => NULL,
          'border-top-style' => NULL,
          'border-bottom-style' => NULL,
          'border-diagonal-style' => NULL,
        ),
      ),
      'f' => NULL,
      't' => 'string',
      'o' => 'Data of Sheet1',
    ),
    'C' => 
    array (
      'v' => NULL,
      's' => 
      array (
        'format' => 
        array (
          'format-num-id' => 0,
          'format-pattern' => 'General',
          'format-category' => 'general',
          'format-align-horizontal' => 'center',
        ),
        'font' => 
        array (
          'font-size' => '12',
          'font-color' => '#202020',
          'font-name' => 'Calibri',
          'font-family' => '2',
          'font-scheme' => 'minor',
          'font-style-bold' => 1,
          'font-charset' => '204',
        ),
        'fill' => 
        array (
          'fill-pattern' => 'none',
        ),
        'border' => 
        array (
          'border-left-style' => NULL,
          'border-right-style' => NULL,
          'border-top-style' => NULL,
          'border-bottom-style' => NULL,
          'border-diagonal-style' => NULL,
        ),
      ),
      'f' => NULL,
      't' => '',
      'o' => NULL,
    ),
    'D' => 
    array (
      'v' => NULL,
      's' => 
      array (
        'format' => 
        array (
          'format-num-id' => 0,
          'format-pattern' => 'General',
          'format-category' => 'general',
          'format-align-horizontal' => 'center',
        ),
        'font' => 
        array (
          'font-size' => '12',
          'font-color' => '#202020',
          'font-name' => 'Calibri',
          'font-family' => '2',
          'font-scheme' => 'minor',
          'font-style-bold' => 1,
          'font-charset' => '204',
        ),
        'fill' => 
        array (
          'fill-pattern' => 'none',
        ),
        'border' => 
        array (
          'border-left-style' => NULL,
          'border-right-style' => NULL,
          'border-top-style' => NULL,
          'border-bottom-style' => NULL,
          'border-diagonal-style' => NULL,
        ),
      ),
      'f' => NULL,
      't' => '',
      'o' => NULL,
    ),
  ),
  4 => 
  array (
    'B' => 
    array (
      'v' => 'Name',
      's' => 
      array (
        'format' => 
        array (
          'format-num-id' => 0,
          'format-pattern' => 'General',
          'format-category' => 'general',
        ),
        'font' => 
        array (
          'font-size' => '11',
          'font-color' => '#202020',
          'font-name' => 'Calibri',
          'font-family' => '2',
          'font-scheme' => 'minor',
          'font-style-bold' => 1,
          'font-charset' => '204',
        ),
        'fill' => 
        array (
          'fill-pattern' => 'none',
        ),
        'border' => 
        array (
          'border-left-style' => NULL,
          'border-right-style' => NULL,
          'border-top-style' => NULL,
          'border-bottom-style' => NULL,
          'border-diagonal-style' => NULL,
        ),
      ),
      'f' => NULL,
      't' => 'string',
      'o' => 'Name',
    ),
    'C' => 
    array (
      'v' => 'Date',
      's' => 
      array (
        'format' => 
        array (
          'format-num-id' => 0,
          'format-pattern' => 'General',
          'format-category' => 'general',
        ),
        'font' => 
        array (
          'font-size' => '11',
          'font-color' => '#202020',
          'font-name' => 'Calibri',
          'font-family' => '2',
          'font-scheme' => 'minor',
          'font-style-bold' => 1,
          'font-charset' => '204',
        ),
        'fill' => 
        array (
          'fill-pattern' => 'none',
        ),
        'border' => 
        array (
          'border-left-style' => NULL,
          'border-right-style' => NULL,
          'border-top-style' => NULL,
          'border-bottom-style' => NULL,
          'border-diagonal-style' => NULL,
        ),
      ),
      'f' => NULL,
      't' => 'string',
      'o' => 'Date',
    ),
    'D' => 
    array (
      'v' => 'Color',
      's' => 
      array (
        'format' => 
        array (
          'format-num-id' => 0,
          'format-pattern' => 'General',
          'format-category' => 'general',
        ),
        'font' => 
        array (
          'font-size' => '11',
          'font-color' => '#202020',
          'font-name' => 'Calibri',
          'font-family' => '2',
          'font-scheme' => 'minor',
          'font-style-bold' => 1,
          'font-charset' => '204',
        ),
        'fill' => 
        array (
          'fill-pattern' => 'none',
        ),
        'border' => 
        array (
          'border-left-style' => NULL,
          'border-right-style' => NULL,
          'border-top-style' => NULL,
          'border-bottom-style' => NULL,
          'border-diagonal-style' => NULL,
        ),
      ),
      'f' => NULL,
      't' => 'string',
      'o' => 'Color',
    ),
  ),
  5 => 
  array (
    'B' => 
    array (
      'v' => 'Giovanni',
      's' => 
      array (
        'format' => 
        array (
          'format-num-id' => 49,
          'format-pattern' => '@',
          'format-category' => 'string',
          'format-align-vertical' => 'top',
        ),
        'font' => 
        array (
          'font-size' => '10',
          'font-color' => '#202020',
          'font-name' => 'Arial',
          'font-family' => '2',
          'font-scheme' => 'minor',
          'font-charset' => '1',
        ),
        'fill' => 
        array (
          'fill-pattern' => 'none',
        ),
        'border' => 
        array (
          'border-left-style' => NULL,
          'border-right-style' => NULL,
          'border-top-style' => NULL,
          'border-bottom-style' => NULL,
          'border-diagonal-style' => NULL,
        ),
      ),
      'f' => NULL,
      't' => 'string',
      'o' => 'Giovanni',
    ),
    'C' => 
    array (
      'v' => 18316800,
      's' => 
      array (
        'format' => 
        array (
          'format-num-id' => 14,
          'format-pattern' => 'm/d/yy',
          'format-category' => 'date',
        ),
        'font' => 
        array (
          'font-size' => '11',
          'font-color' => '#202020',
          'font-name' => 'Calibri',
          'font-family' => '2',
          'font-scheme' => 'minor',
        ),
        'fill' => 
        array (
          'fill-pattern' => 'none',
        ),
        'border' => 
        array (
          'border-left-style' => NULL,
          'border-right-style' => NULL,
          'border-top-style' => NULL,
          'border-bottom-style' => NULL,
          'border-diagonal-style' => NULL,
        ),
      ),
      'f' => NULL,
      't' => 'date',
      'o' => '25781',
    ),
    'D' => 
    array (
      'v' => 'Red',
      's' => 
      array (
        'format' => 
        array (
          'format-num-id' => 0,
          'format-pattern' => 'General',
          'format-category' => 'general',
          'format-align-horizontal' => 'center',
        ),
        'font' => 
        array (
          'font-size' => '11',
          'font-color' => '#202020',
          'font-name' => 'Calibri',
          'font-family' => '2',
          'font-scheme' => 'minor',
        ),
        'fill' => 
        array (
          'fill-pattern' => 'none',
        ),
        'border' => 
        array (
          'border-left-style' => NULL,
          'border-right-style' => NULL,
          'border-top-style' => NULL,
          'border-bottom-style' => NULL,
          'border-diagonal-style' => NULL,
        ),
      ),
      'f' => NULL,
      't' => 'string',
      'o' => 'Red',
    ),
  ),
);
