<?php

// Snapshot: styles--complete-by-idx
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  0 => 
  array (
    'nested' => 
    array (
      'format' => 
      array (
        'format-num-id' => 0,
        'format-pattern' => 'General',
        'format-category' => 'general',
      ),
      'font' => 
      array (
        'font-size' => '10',
        'font-name' => 'Arial',
        'font-family' => '2',
        'font-charset' => '1',
      ),
      'fill' => 
      array (
        'fill-pattern' => 'none',
      ),
      'border' => 
      array (
        'border-left-style' => NULL,
        'border-right-style' => NULL,
        'border-top-style' => NULL,
        'border-bottom-style' => NULL,
        'border-diagonal-style' => NULL,
      ),
    ),
    'flat' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
      'fill-pattern' => 'none',
      'border-left-style' => NULL,
      'border-right-style' => NULL,
      'border-top-style' => NULL,
      'border-bottom-style' => NULL,
      'border-diagonal-style' => NULL,
    ),
    'pattern' => 'General',
  ),
  1 => 
  array (
    'nested' => 
    array (
      'format' => 
      array (
        'format-num-id' => 0,
        'format-pattern' => 'General',
        'format-category' => 'general',
      ),
      'font' => 
      array (
        'font-size' => '10',
        'font-name' => 'Arial',
        'font-family' => '2',
        'font-charset' => '1',
      ),
      'fill' => 
      array (
        'fill-pattern' => 'solid',
        'fill-color' => '#9FC63C',
      ),
      'border' => 
      array (
        'border-left-style' => NULL,
        'border-right-style' => NULL,
        'border-top-style' => NULL,
        'border-bottom-style' => NULL,
        'border-diagonal-style' => NULL,
      ),
    ),
    'flat' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
      'fill-pattern' => 'solid',
      'fill-color' => '#9FC63C',
      'border-left-style' => NULL,
      'border-right-style' => NULL,
      'border-top-style' => NULL,
      'border-bottom-style' => NULL,
      'border-diagonal-style' => NULL,
    ),
    'pattern' => 'General',
  ),
  2 => 
  array (
    'nested' => 
    array (
      'format' => 
      array (
        'format-num-id' => 0,
        'format-pattern' => 'General',
        'format-category' => 'general',
      ),
      'font' => 
      array (
        'font-size' => '10',
        'font-name' => 'Arial',
        'font-family' => '2',
        'font-charset' => '1',
      ),
      'fill' => 
      array (
        'fill-pattern' => 'solid',
        'fill-color' => '#3C636F',
      ),
      'border' => 
      array (
        'border-left-style' => NULL,
        'border-right-style' => NULL,
        'border-top-style' => NULL,
        'border-bottom-style' => NULL,
        'border-diagonal-style' => NULL,
      ),
    ),
    'flat' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
      'fill-pattern' => 'solid',
      'fill-color' => '#3C636F',
      'border-left-style' => NULL,
      'border-right-style' => NULL,
      'border-top-style' => NULL,
      'border-bottom-style' => NULL,
      'border-diagonal-style' => NULL,
    ),
    'pattern' => 'General',
  ),
  3 => 
  array (
    'nested' => 
    array (
      'format' => 
      array (
        'format-num-id' => 0,
        'format-pattern' => 'General',
        'format-category' => 'general',
      ),
      'font' => 
      array (
        'font-size' => '10',
        'font-name' => 'Arial',
        'font-family' => '2',
        'font-charset' => '1',
      ),
      'fill' => 
      array (
        'fill-pattern' => 'solid',
        'fill-color' => '#9FC3F6',
      ),
      'border' => 
      array (
        'border-left-style' => NULL,
        'border-right-style' => NULL,
        'border-top-style' => NULL,
        'border-bottom-style' => NULL,
        'border-diagonal-style' => NULL,
      ),
    ),
    'flat' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
      'fill-pattern' => 'solid',
      'fill-color' => '#9FC3F6',
      'border-left-style' => NULL,
      'border-right-style' => NULL,
      'border-top-style' => NULL,
      'border-bottom-style' => NULL,
      'border-diagonal-style' => NULL,
    ),
    'pattern' => 'General',
  ),
  5 => 
  array (
    'nested' => 
    array (
      'format' => 
      array (
        'format-num-id' => 0,
        'format-pattern' => 'General',
        'format-category' => 'general',
      ),
      'font' => 
      array (
        'font-size' => '10',
        'font-name' => 'Arial',
        'font-family' => '2',
        'font-charset' => '1',
      ),
      'fill' => 
      array (
        'fill-pattern' => 'solid',
        'fill-color' => '#3C69CF',
      ),
      'border' => 
      array (
        'border-left-style' => NULL,
        'border-right-style' => NULL,
        'border-top-style' => NULL,
        'border-bottom-style' => NULL,
        'border-diagonal-style' => NULL,
      ),
    ),
    'flat' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
      'fill-pattern' => 'solid',
      'fill-color' => '#3C69CF',
      'border-left-style' => NULL,
      'border-right-style' => NULL,
      'border-top-style' => NULL,
      'border-bottom-style' => NULL,
      'border-diagonal-style' => NULL,
    ),
    'pattern' => 'General',
  ),
  8 => 
  array (
    'nested' => 
    array (
      'format' => 
      array (
        'format-num-id' => 0,
        'format-pattern' => 'General',
        'format-category' => 'general',
      ),
      'font' => 
      array (
        'font-size' => '10',
        'font-name' => 'Arial',
        'font-family' => '2',
        'font-charset' => '1',
      ),
      'fill' => 
      array (
        'fill-pattern' => 'solid',
        'fill-color' => '#9CF36F',
      ),
      'border' => 
      array (
        'border-left-style' => NULL,
        'border-right-style' => NULL,
        'border-top-style' => NULL,
        'border-bottom-style' => NULL,
        'border-diagonal-style' => NULL,
      ),
    ),
    'flat' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
      'fill-pattern' => 'solid',
      'fill-color' => '#9CF36F',
      'border-left-style' => NULL,
      'border-right-style' => NULL,
      'border-top-style' => NULL,
      'border-bottom-style' => NULL,
      'border-diagonal-style' => NULL,
    ),
    'pattern' => 'General',
  ),
);
