<?php

// Snapshot: styles--cell-styles-nested
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  'A1' => 
  array (
    'format' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
    ),
    'font' => 
    array (
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
    ),
    'fill' => 
    array (
      'fill-pattern' => 'solid',
      'fill-color' => '#9FC63C',
    ),
    'border' => 
    array (
      'border-left-style' => NULL,
      'border-right-style' => NULL,
      'border-top-style' => NULL,
      'border-bottom-style' => NULL,
      'border-diagonal-style' => NULL,
    ),
  ),
  'B1' => 
  array (
    'format' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
    ),
    'font' => 
    array (
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
    ),
    'fill' => 
    array (
      'fill-pattern' => 'solid',
      'fill-color' => '#3C636F',
    ),
    'border' => 
    array (
      'border-left-style' => NULL,
      'border-right-style' => NULL,
      'border-top-style' => NULL,
      'border-bottom-style' => NULL,
      'border-diagonal-style' => NULL,
    ),
  ),
  'C1' => 
  array (
    'format' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
    ),
    'font' => 
    array (
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
    ),
    'fill' => 
    array (
      'fill-pattern' => 'solid',
      'fill-color' => '#9FC3F6',
    ),
    'border' => 
    array (
      'border-left-style' => NULL,
      'border-right-style' => NULL,
      'border-top-style' => NULL,
      'border-bottom-style' => NULL,
      'border-diagonal-style' => NULL,
    ),
  ),
  'D1' => 
  array (
    'format' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
    ),
    'font' => 
    array (
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
    ),
    'fill' => 
    array (
      'fill-pattern' => 'solid',
      'fill-color' => '#63FC9F',
    ),
    'border' => 
    array (
      'border-left-style' => NULL,
      'border-right-style' => NULL,
      'border-top-style' => NULL,
      'border-bottom-style' => NULL,
      'border-diagonal-style' => NULL,
    ),
  ),
  'E1' => 
  array (
    'format' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
    ),
    'font' => 
    array (
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
    ),
    'fill' => 
    array (
      'fill-pattern' => 'solid',
      'fill-color' => '#3C69CF',
    ),
    'border' => 
    array (
      'border-left-style' => NULL,
      'border-right-style' => NULL,
      'border-top-style' => NULL,
      'border-bottom-style' => NULL,
      'border-diagonal-style' => NULL,
    ),
  ),
  'A2' => 
  array (
    'format' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
      'format-align-horizontal' => 'center',
      'format-align-vertical' => 'center',
    ),
    'font' => 
    array (
      'font-size' => '24',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
      'font-style-bold' => 1,
    ),
    'fill' => 
    array (
      'fill-pattern' => 'none',
    ),
    'border' => 
    array (
      'border-left-style' => NULL,
      'border-right-style' => NULL,
      'border-top-style' => NULL,
      'border-bottom-style' => NULL,
      'border-diagonal-style' => NULL,
    ),
  ),
  'B2' => 
  array (
    'format' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
    ),
    'font' => 
    array (
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
    ),
    'fill' => 
    array (
      'fill-pattern' => 'none',
    ),
    'border' => 
    array (
      'border-left-style' => NULL,
      'border-right-style' => NULL,
      'border-top-style' => NULL,
      'border-bottom-style' => NULL,
      'border-diagonal-style' => NULL,
    ),
  ),
  'C2' => 
  array (
    'format' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
    ),
    'font' => 
    array (
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
    ),
    'fill' => 
    array (
      'fill-pattern' => 'none',
    ),
    'border' => 
    array (
      'border-left-style' => NULL,
      'border-right-style' => NULL,
      'border-top-style' => NULL,
      'border-bottom-style' => NULL,
      'border-diagonal-style' => NULL,
    ),
  ),
  'D2' => 
  array (
    'format' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
    ),
    'font' => 
    array (
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
    ),
    'fill' => 
    array (
      'fill-pattern' => 'none',
    ),
    'border' => 
    array (
      'border-left-style' => NULL,
      'border-right-style' => NULL,
      'border-top-style' => NULL,
      'border-bottom-style' => NULL,
      'border-diagonal-style' => NULL,
    ),
  ),
  'E2' => 
  array (
    'format' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
    ),
    'font' => 
    array (
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
    ),
    'fill' => 
    array (
      'fill-pattern' => 'none',
    ),
    'border' => 
    array (
      'border-left-style' => NULL,
      'border-right-style' => NULL,
      'border-top-style' => NULL,
      'border-bottom-style' => NULL,
      'border-diagonal-style' => NULL,
    ),
  ),
  'A3' => 
  array (
  ),
  'B3' => 
  array (
  ),
  'C3' => 
  array (
  ),
  'D3' => 
  array (
  ),
  'E3' => 
  array (
    'format' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
      'format-align-horizontal' => 'center',
      'format-align-vertical' => 'center',
    ),
    'font' => 
    array (
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
      'font-style-underline' => 1,
      'font-color' => '#0563C1',
    ),
    'fill' => 
    array (
      'fill-pattern' => 'none',
    ),
    'border' => 
    array (
      'border-left-style' => NULL,
      'border-right-style' => NULL,
      'border-top-style' => NULL,
      'border-bottom-style' => NULL,
      'border-diagonal-style' => NULL,
    ),
  ),
  'A4' => 
  array (
  ),
  'B4' => 
  array (
  ),
  'C4' => 
  array (
  ),
  'D4' => 
  array (
  ),
  'E4' => 
  array (
  ),
  'A6' => 
  array (
    'format' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
      'format-align-horizontal' => 'center',
      'format-align-vertical' => 'center',
    ),
    'font' => 
    array (
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
      'font-style-bold' => 1,
    ),
    'fill' => 
    array (
      'fill-pattern' => 'solid',
      'fill-color' => '#EEEEEE',
    ),
    'border' => 
    array (
      'border-left-style' => 'thick',
      'border-right-style' => 'thin',
      'border-top-style' => 'thick',
      'border-bottom-style' => 'thin',
      'border-diagonal-style' => NULL,
      'border-left-color' => '#000000',
      'border-right-color' => '#000000',
      'border-top-color' => '#000000',
      'border-bottom-color' => '#000000',
    ),
  ),
  'B6' => 
  array (
    'format' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
      'format-align-horizontal' => 'center',
      'format-align-vertical' => 'center',
    ),
    'font' => 
    array (
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
      'font-style-bold' => 1,
    ),
    'fill' => 
    array (
      'fill-pattern' => 'solid',
      'fill-color' => '#EEEEEE',
    ),
    'border' => 
    array (
      'border-left-style' => 'thin',
      'border-right-style' => 'thin',
      'border-top-style' => 'thick',
      'border-bottom-style' => 'thin',
      'border-diagonal-style' => NULL,
      'border-left-color' => '#000000',
      'border-right-color' => '#000000',
      'border-top-color' => '#000000',
      'border-bottom-color' => '#000000',
    ),
  ),
  'C6' => 
  array (
    'format' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
      'format-align-horizontal' => 'center',
      'format-align-vertical' => 'center',
    ),
    'font' => 
    array (
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
      'font-style-bold' => 1,
    ),
    'fill' => 
    array (
      'fill-pattern' => 'solid',
      'fill-color' => '#EEEEEE',
    ),
    'border' => 
    array (
      'border-left-style' => 'thin',
      'border-right-style' => 'thin',
      'border-top-style' => 'thick',
      'border-bottom-style' => 'thin',
      'border-diagonal-style' => NULL,
      'border-left-color' => '#000000',
      'border-right-color' => '#000000',
      'border-top-color' => '#000000',
      'border-bottom-color' => '#000000',
    ),
  ),
  'D6' => 
  array (
    'format' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
      'format-align-horizontal' => 'center',
      'format-align-vertical' => 'center',
    ),
    'font' => 
    array (
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
      'font-style-bold' => 1,
    ),
    'fill' => 
    array (
      'fill-pattern' => 'solid',
      'fill-color' => '#EEEEEE',
    ),
    'border' => 
    array (
      'border-left-style' => 'thin',
      'border-right-style' => 'thin',
      'border-top-style' => 'thick',
      'border-bottom-style' => 'thin',
      'border-diagonal-style' => NULL,
      'border-left-color' => '#000000',
      'border-right-color' => '#000000',
      'border-top-color' => '#000000',
      'border-bottom-color' => '#000000',
    ),
  ),
  'E6' => 
  array (
    'format' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
      'format-align-horizontal' => 'center',
      'format-align-vertical' => 'center',
    ),
    'font' => 
    array (
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
      'font-style-bold' => 1,
    ),
    'fill' => 
    array (
      'fill-pattern' => 'solid',
      'fill-color' => '#EEEEEE',
    ),
    'border' => 
    array (
      'border-left-style' => 'thin',
      'border-right-style' => 'thin',
      'border-top-style' => 'thick',
      'border-bottom-style' => 'thin',
      'border-diagonal-style' => NULL,
      'border-left-color' => '#000000',
      'border-right-color' => '#000000',
      'border-top-color' => '#000000',
      'border-bottom-color' => '#000000',
    ),
  ),
  'A7' => 
  array (
    'format' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
      'format-align-horizontal' => 'center',
      'format-align-vertical' => 'center',
    ),
    'font' => 
    array (
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
      'font-style-bold' => 1,
    ),
    'fill' => 
    array (
      'fill-pattern' => 'solid',
      'fill-color' => '#EEEEEE',
    ),
    'border' => 
    array (
      'border-left-style' => 'thick',
      'border-right-style' => 'thin',
      'border-top-style' => 'thin',
      'border-bottom-style' => 'thick',
      'border-diagonal-style' => NULL,
      'border-left-color' => '#000000',
      'border-right-color' => '#000000',
      'border-top-color' => '#000000',
      'border-bottom-color' => '#000000',
    ),
  ),
  'B7' => 
  array (
    'format' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
      'format-align-horizontal' => 'center',
      'format-align-vertical' => 'center',
    ),
    'font' => 
    array (
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
      'font-style-bold' => 1,
    ),
    'fill' => 
    array (
      'fill-pattern' => 'solid',
      'fill-color' => '#EEEEEE',
    ),
    'border' => 
    array (
      'border-left-style' => 'thin',
      'border-right-style' => 'thin',
      'border-top-style' => 'thin',
      'border-bottom-style' => 'thick',
      'border-diagonal-style' => NULL,
      'border-left-color' => '#000000',
      'border-right-color' => '#000000',
      'border-top-color' => '#000000',
      'border-bottom-color' => '#000000',
    ),
  ),
  'C7' => 
  array (
    'format' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
      'format-align-horizontal' => 'center',
      'format-align-vertical' => 'center',
    ),
    'font' => 
    array (
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
      'font-style-bold' => 1,
    ),
    'fill' => 
    array (
      'fill-pattern' => 'solid',
      'fill-color' => '#EEEEEE',
    ),
    'border' => 
    array (
      'border-left-style' => 'thin',
      'border-right-style' => 'thin',
      'border-top-style' => 'thin',
      'border-bottom-style' => 'thick',
      'border-diagonal-style' => NULL,
      'border-left-color' => '#000000',
      'border-right-color' => '#000000',
      'border-top-color' => '#000000',
      'border-bottom-color' => '#000000',
    ),
  ),
  'D7' => 
  array (
    'format' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
      'format-align-horizontal' => 'center',
      'format-align-vertical' => 'center',
    ),
    'font' => 
    array (
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
      'font-style-bold' => 1,
    ),
    'fill' => 
    array (
      'fill-pattern' => 'solid',
      'fill-color' => '#EEEEEE',
    ),
    'border' => 
    array (
      'border-left-style' => 'thin',
      'border-right-style' => 'thin',
      'border-top-style' => 'thin',
      'border-bottom-style' => 'thick',
      'border-diagonal-style' => NULL,
      'border-left-color' => '#000000',
      'border-right-color' => '#000000',
      'border-top-color' => '#000000',
      'border-bottom-color' => '#000000',
    ),
  ),
  'E7' => 
  array (
    'format' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
      'format-align-horizontal' => 'center',
      'format-align-vertical' => 'center',
    ),
    'font' => 
    array (
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
      'font-style-bold' => 1,
    ),
    'fill' => 
    array (
      'fill-pattern' => 'solid',
      'fill-color' => '#EEEEEE',
    ),
    'border' => 
    array (
      'border-left-style' => 'thin',
      'border-right-style' => 'thin',
      'border-top-style' => 'thin',
      'border-bottom-style' => 'thick',
      'border-diagonal-style' => NULL,
      'border-left-color' => '#000000',
      'border-right-color' => '#000000',
      'border-top-color' => '#000000',
      'border-bottom-color' => '#000000',
    ),
  ),
  'A8' => 
  array (
    'format' => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
      'format-align-vertical' => 'top',
    ),
    'font' => 
    array (
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
    ),
    'fill' => 
    array (
      'fill-pattern' => 'none',
    ),
    'border' => 
    array (
      'border-left-style' => NULL,
      'border-right-style' => NULL,
      'border-top-style' => NULL,
      'border-bottom-style' => NULL,
      'border-diagonal-style' => NULL,
    ),
  ),
  'B8' => 
  array (
    'format' => 
    array (
      'format-num-id' => 49,
      'format-pattern' => '@',
      'format-category' => 'string',
      'format-align-vertical' => 'top',
    ),
    'font' => 
    array (
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
    ),
    'fill' => 
    array (
      'fill-pattern' => 'none',
    ),
    'border' => 
    array (
      'border-left-style' => NULL,
      'border-right-style' => NULL,
      'border-top-style' => NULL,
      'border-bottom-style' => NULL,
      'border-diagonal-style' => NULL,
    ),
  ),
  'C8' => 
  array (
    'format' => 
    array (
      'format-num-id' => 49,
      'format-pattern' => '@',
      'format-category' => 'string',
      'format-align-vertical' => 'top',
    ),
    'font' => 
    array (
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
    ),
    'fill' => 
    array (
      'fill-pattern' => 'none',
    ),
    'border' => 
    array (
      'border-left-style' => NULL,
      'border-right-style' => NULL,
      'border-top-style' => NULL,
      'border-bottom-style' => NULL,
      'border-diagonal-style' => NULL,
    ),
  ),
  'D8' => 
  array (
    'format' => 
    array (
      'format-num-id' => 165,
      'format-pattern' => 'dd\\.mm\\.yyyy',
      'format-category' => 'date',
      'format-align-vertical' => 'top',
    ),
    'font' => 
    array (
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
    ),
    'fill' => 
    array (
      'fill-pattern' => 'none',
    ),
    'border' => 
    array (
      'border-left-style' => NULL,
      'border-right-style' => NULL,
      'border-top-style' => NULL,
      'border-bottom-style' => NULL,
      'border-diagonal-style' => NULL,
    ),
  ),
  'E8' => 
  array (
    'format' => 
    array (
      'format-num-id' => 1,
      'format-pattern' => '0',
      'format-category' => 'number',
      'format-align-vertical' => 'top',
    ),
    'font' => 
    array (
      'font-size' => '10',
      'font-name' => 'Arial',
      'font-family' => '2',
      'font-charset' => '1',
    ),
    'fill' => 
    array (
      'fill-pattern' => 'none',
    ),
    'border' => 
    array (
      'border-left-style' => NULL,
      'border-right-style' => NULL,
      'border-top-style' => NULL,
      'border-bottom-style' => NULL,
      'border-diagonal-style' => NULL,
    ),
  ),
);
