<?php

// Snapshot: styles--cells-with-styles-key
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  'A1' => 
  array (
    'v' => NULL,
    's' => 
    array (
      'fill-color' => '#9FC63C',
    ),
    'f' => NULL,
    't' => '',
    'o' => NULL,
  ),
  'B1' => 
  array (
    'v' => NULL,
    's' => 
    array (
      'fill-color' => '#3C636F',
    ),
    'f' => NULL,
    't' => '',
    'o' => NULL,
  ),
  'C1' => 
  array (
    'v' => NULL,
    's' => 
    array (
      'fill-color' => '#9FC3F6',
    ),
    'f' => NULL,
    't' => '',
    'o' => NULL,
  ),
  'D1' => 
  array (
    'v' => NULL,
    's' => 
    array (
      'fill-color' => '#63FC9F',
    ),
    'f' => NULL,
    't' => '',
    'o' => NULL,
  ),
  'E1' => 
  array (
    'v' => NULL,
    's' => 
    array (
      'fill-color' => '#3C69CF',
    ),
    'f' => NULL,
    't' => '',
    'o' => NULL,
  ),
  'A2' => 
  array (
    'v' => 'This is demo XLSX-sheet',
    's' => 
    array (
      'format' => 
      array (
        'format-num-id' => 0,
        'format-pattern' => 'General',
        'format-category' => 'general',
        'format-align-horizontal' => 'center',
        'format-align-vertical' => 'center',
      ),
      'font' => 
      array (
        'font-size' => '24',
        'font-name' => 'Arial',
        'font-family' => '2',
        'font-charset' => '1',
        'font-style-bold' => 1,
      ),
      'fill' => 
      array (
        'fill-pattern' => 'none',
      ),
      'border' => 
      array (
        'border-left-style' => NULL,
        'border-right-style' => NULL,
        'border-top-style' => NULL,
        'border-bottom-style' => NULL,
        'border-diagonal-style' => NULL,
      ),
    ),
    'f' => NULL,
    't' => 'string',
    'o' => 'This is demo XLSX-sheet',
  ),
  'B2' => 
  array (
    'v' => NULL,
    's' => 
    array (
      'format' => 
      array (
        'format-num-id' => 0,
        'format-pattern' => 'General',
        'format-category' => 'general',
      ),
      'font' => 
      array (
        'font-size' => '10',
        'font-name' => 'Arial',
        'font-family' => '2',
        'font-charset' => '1',
      ),
      'fill' => 
      array (
        'fill-pattern' => 'none',
      ),
      'border' => 
      array (
        'border-left-style' => NULL,
        'border-right-style' => NULL,
        'border-top-style' => NULL,
        'border-bottom-style' => NULL,
        'border-diagonal-style' => NULL,
      ),
    ),
    'f' => NULL,
    't' => '',
    'o' => NULL,
  ),
  'C2' => 
  array (
    'v' => NULL,
    's' => 
    array (
      'format' => 
      array (
        'format-num-id' => 0,
        'format-pattern' => 'General',
        'format-category' => 'general',
      ),
      'font' => 
      array (
        'font-size' => '10',
        'font-name' => 'Arial',
        'font-family' => '2',
        'font-charset' => '1',
      ),
      'fill' => 
      array (
        'fill-pattern' => 'none',
      ),
      'border' => 
      array (
        'border-left-style' => NULL,
        'border-right-style' => NULL,
        'border-top-style' => NULL,
        'border-bottom-style' => NULL,
        'border-diagonal-style' => NULL,
      ),
    ),
    'f' => NULL,
    't' => '',
    'o' => NULL,
  ),
  'D2' => 
  array (
    'v' => NULL,
    's' => 
    array (
      'format' => 
      array (
        'format-num-id' => 0,
        'format-pattern' => 'General',
        'format-category' => 'general',
      ),
      'font' => 
      array (
        'font-size' => '10',
        'font-name' => 'Arial',
        'font-family' => '2',
        'font-charset' => '1',
      ),
      'fill' => 
      array (
        'fill-pattern' => 'none',
      ),
      'border' => 
      array (
        'border-left-style' => NULL,
        'border-right-style' => NULL,
        'border-top-style' => NULL,
        'border-bottom-style' => NULL,
        'border-diagonal-style' => NULL,
      ),
    ),
    'f' => NULL,
    't' => '',
    'o' => NULL,
  ),
  'E2' => 
  array (
    'v' => NULL,
    's' => 
    array (
      'format' => 
      array (
        'format-num-id' => 0,
        'format-pattern' => 'General',
        'format-category' => 'general',
      ),
      'font' => 
      array (
        'font-size' => '10',
        'font-name' => 'Arial',
        'font-family' => '2',
        'font-charset' => '1',
      ),
      'fill' => 
      array (
        'fill-pattern' => 'none',
      ),
      'border' => 
      array (
        'border-left-style' => NULL,
        'border-right-style' => NULL,
        'border-top-style' => NULL,
        'border-bottom-style' => NULL,
        'border-diagonal-style' => NULL,
      ),
    ),
    'f' => NULL,
    't' => '',
    'o' => NULL,
  ),
  'A3' => NULL,
  'B3' => NULL,
  'C3' => NULL,
  'D3' => NULL,
  'E3' => 
  array (
    'v' => 'avadim/fast-excel-writer',
    's' => 
    array (
      'format' => 
      array (
        'format-num-id' => 0,
        'format-pattern' => 'General',
        'format-category' => 'general',
        'format-align-horizontal' => 'center',
        'format-align-vertical' => 'center',
      ),
      'font' => 
      array (
        'font-size' => '10',
        'font-name' => 'Arial',
        'font-family' => '2',
        'font-charset' => '1',
        'font-style-underline' => 1,
        'font-color' => '#0563C1',
      ),
      'fill' => 
      array (
        'fill-pattern' => 'none',
      ),
      'border' => 
      array (
        'border-left-style' => NULL,
        'border-right-style' => NULL,
        'border-top-style' => NULL,
        'border-bottom-style' => NULL,
        'border-diagonal-style' => NULL,
      ),
    ),
    'f' => NULL,
    't' => 'string',
    'o' => 'avadim/fast-excel-writer',
  ),
  'A4' => NULL,
  'B4' => NULL,
  'C4' => NULL,
  'D4' => NULL,
  'E4' => NULL,
  'A6' => 
  array (
    'v' => '#',
    's' => 
    array (
      'fill-color' => '#EEEEEE',
    ),
    'f' => NULL,
    't' => 'string',
    'o' => '#',
  ),
  'B6' => 
  array (
    'v' => 'People',
    's' => 
    array (
      'fill-color' => '#EEEEEE',
    ),
    'f' => NULL,
    't' => 'string',
    'o' => 'People',
  ),
  'C6' => 
  array (
    'v' => NULL,
    's' => 
    array (
      'fill-color' => '#EEEEEE',
    ),
    'f' => NULL,
    't' => '',
    'o' => NULL,
  ),
  'D6' => 
  array (
    'v' => 'Birthday',
    's' => 
    array (
      'fill-color' => '#EEEEEE',
    ),
    'f' => NULL,
    't' => 'string',
    'o' => 'Birthday',
  ),
  'E6' => 
  array (
    'v' => 'Age',
    's' => 
    array (
      'fill-color' => '#EEEEEE',
    ),
    'f' => NULL,
    't' => 'string',
    'o' => 'Age',
  ),
  'A7' => 
  array (
    'v' => NULL,
    's' => 
    array (
      'fill-color' => '#EEEEEE',
    ),
    'f' => NULL,
    't' => '',
    'o' => NULL,
  ),
  'B7' => 
  array (
    'v' => 'First Name',
    's' => 
    array (
      'fill-color' => '#EEEEEE',
    ),
    'f' => NULL,
    't' => 'string',
    'o' => 'First Name',
  ),
  'C7' => 
  array (
    'v' => 'Last Name',
    's' => 
    array (
      'fill-color' => '#EEEEEE',
    ),
    'f' => NULL,
    't' => 'string',
    'o' => 'Last Name',
  ),
  'D7' => 
  array (
    'v' => NULL,
    's' => 
    array (
      'fill-color' => '#EEEEEE',
    ),
    'f' => NULL,
    't' => '',
    'o' => NULL,
  ),
  'E7' => 
  array (
    'v' => NULL,
    's' => 
    array (
      'fill-color' => '#EEEEEE',
    ),
    'f' => NULL,
    't' => '',
    'o' => NULL,
  ),
  'A8' => 
  array (
    'v' => 1,
    's' => 
    array (
      'format' => 
      array (
        'format-num-id' => 0,
        'format-pattern' => 'General',
        'format-category' => 'general',
        'format-align-vertical' => 'top',
      ),
      'font' => 
      array (
        'font-size' => '10',
        'font-name' => 'Arial',
        'font-family' => '2',
        'font-charset' => '1',
      ),
      'fill' => 
      array (
        'fill-pattern' => 'none',
      ),
      'border' => 
      array (
        'border-left-style' => NULL,
        'border-right-style' => NULL,
        'border-top-style' => NULL,
        'border-bottom-style' => NULL,
        'border-diagonal-style' => NULL,
      ),
    ),
    'f' => NULL,
    't' => 'number',
    'o' => '1',
  ),
  'B8' => 
  array (
    'v' => 'Evan',
    's' => 
    array (
      'format' => 
      array (
        'format-num-id' => 49,
        'format-pattern' => '@',
        'format-category' => 'string',
        'format-align-vertical' => 'top',
      ),
      'font' => 
      array (
        'font-size' => '10',
        'font-name' => 'Arial',
        'font-family' => '2',
        'font-charset' => '1',
      ),
      'fill' => 
      array (
        'fill-pattern' => 'none',
      ),
      'border' => 
      array (
        'border-left-style' => NULL,
        'border-right-style' => NULL,
        'border-top-style' => NULL,
        'border-bottom-style' => NULL,
        'border-diagonal-style' => NULL,
      ),
    ),
    'f' => NULL,
    't' => 'string',
    'o' => 'Evan',
  ),
  'C8' => 
  array (
    'v' => 'Schmidt',
    's' => 
    array (
      'format' => 
      array (
        'format-num-id' => 49,
        'format-pattern' => '@',
        'format-category' => 'string',
        'format-align-vertical' => 'top',
      ),
      'font' => 
      array (
        'font-size' => '10',
        'font-name' => 'Arial',
        'font-family' => '2',
        'font-charset' => '1',
      ),
      'fill' => 
      array (
        'fill-pattern' => 'none',
      ),
      'border' => 
      array (
        'border-left-style' => NULL,
        'border-right-style' => NULL,
        'border-top-style' => NULL,
        'border-bottom-style' => NULL,
        'border-diagonal-style' => NULL,
      ),
    ),
    'f' => NULL,
    't' => 'string',
    'o' => 'Schmidt',
  ),
  'D8' => 
  array (
    'v' => -893635200,
    's' => 
    array (
      'format' => 
      array (
        'format-num-id' => 165,
        'format-pattern' => 'dd\\.mm\\.yyyy',
        'format-category' => 'date',
        'format-align-vertical' => 'top',
      ),
      'font' => 
      array (
        'font-size' => '10',
        'font-name' => 'Arial',
        'font-family' => '2',
        'font-charset' => '1',
      ),
      'fill' => 
      array (
        'fill-pattern' => 'none',
      ),
      'border' => 
      array (
        'border-left-style' => NULL,
        'border-right-style' => NULL,
        'border-top-style' => NULL,
        'border-bottom-style' => NULL,
        'border-diagonal-style' => NULL,
      ),
    ),
    'f' => NULL,
    't' => 'date',
    'o' => '15226',
  ),
  'E8' => 
  array (
    'v' => 81,
    's' => 
    array (
      'format' => 
      array (
        'format-num-id' => 1,
        'format-pattern' => '0',
        'format-category' => 'number',
        'format-align-vertical' => 'top',
      ),
      'font' => 
      array (
        'font-size' => '10',
        'font-name' => 'Arial',
        'font-family' => '2',
        'font-charset' => '1',
      ),
      'fill' => 
      array (
        'fill-pattern' => 'none',
      ),
      'border' => 
      array (
        'border-left-style' => NULL,
        'border-right-style' => NULL,
        'border-top-style' => NULL,
        'border-bottom-style' => NULL,
        'border-diagonal-style' => NULL,
      ),
    ),
    'f' => '=ROUNDDOWN((TODAY()-D8)/365,0)',
    't' => 'number',
    'o' => '81',
  ),
);
