<?php

// Snapshot: styles--read-styles
// Generated by RefactorGuardTest. Do not edit by hand.

return array (
  'numFmts' => 
  array (
    0 => 
    array (
      'format-num-id' => 0,
      'format-pattern' => 'General',
      'format-category' => 'general',
    ),
    1 => 
    array (
      'format-num-id' => 1,
      'format-pattern' => '0',
      'format-category' => 'number',
    ),
    2 => 
    array (
      'format-num-id' => 2,
      'format-pattern' => '0.00',
      'format-category' => 'number',
    ),
    3 => 
    array (
      'format-num-id' => 3,
      'format-pattern' => '#,##0',
      'format-category' => 'number',
    ),
    4 => 
    array (
      'format-num-id' => 4,
      'format-pattern' => '#,##0.00',
      'format-category' => 'number',
    ),
    9 => 
    array (
      'format-num-id' => 9,
      'format-pattern' => '0%',
      'format-category' => 'number',
    ),
    10 => 
    array (
      'format-num-id' => 10,
      'format-pattern' => '0.00%',
      'format-category' => 'number',
    ),
    11 => 
    array (
      'format-num-id' => 11,
      'format-pattern' => '0.00E+00',
      'format-category' => 'number',
    ),
    12 => 
    array (
      'format-num-id' => 12,
      'format-pattern' => '# ?/?',
      'format-category' => 'general',
    ),
    13 => 
    array (
      'format-num-id' => 13,
      'format-pattern' => '# ??/??',
      'format-category' => 'general',
    ),
    14 => 
    array (
      'format-num-id' => 14,
      'format-pattern' => 'm/d/yy',
      'format-category' => 'date',
    ),
    15 => 
    array (
      'format-num-id' => 15,
      'format-pattern' => 'd/mmm/yy',
      'format-category' => 'date',
    ),
    16 => 
    array (
      'format-num-id' => 16,
      'format-pattern' => 'd/mmm',
      'format-category' => 'date',
    ),
    17 => 
    array (
      'format-num-id' => 17,
      'format-pattern' => 'mmm/yy',
      'format-category' => 'date',
    ),
    18 => 
    array (
      'format-num-id' => 18,
      'format-pattern' => 'h:mm AM/PM',
      'format-category' => 'date',
    ),
    19 => 
    array (
      'format-num-id' => 19,
      'format-pattern' => 'h:mm:ss AM/PM',
      'format-category' => 'date',
    ),
    20 => 
    array (
      'format-num-id' => 20,
      'format-pattern' => 'h:mm a',
      'format-category' => 'date',
    ),
    21 => 
    array (
      'format-num-id' => 21,
      'format-pattern' => 'h:mm:ss a',
      'format-category' => 'date',
    ),
    22 => 
    array (
      'format-num-id' => 22,
      'format-pattern' => 'm/d/yy h:mm a',
      'format-category' => 'date',
    ),
    37 => 
    array (
      'format-num-id' => 37,
      'format-pattern' => '#,##0 ;(#,##0)',
      'format-category' => 'number',
    ),
    38 => 
    array (
      'format-num-id' => 38,
      'format-pattern' => '#,##0 ;[Red](#,##0)',
      'format-category' => 'number',
    ),
    39 => 
    array (
      'format-num-id' => 39,
      'format-pattern' => '#,##0.00;(#,##0.00)',
      'format-category' => 'number',
    ),
    40 => 
    array (
      'format-num-id' => 40,
      'format-pattern' => '#,##0.00;[Red](#,##0.00)',
      'format-category' => 'number',
    ),
    45 => 
    array (
      'format-num-id' => 45,
      'format-pattern' => 'mm:ss',
      'format-category' => 'date',
    ),
    46 => 
    array (
      'format-num-id' => 46,
      'format-pattern' => '[h]:mm:ss',
      'format-category' => 'date',
    ),
    47 => 
    array (
      'format-num-id' => 47,
      'format-pattern' => 'mmss.0',
      'format-category' => 'date',
    ),
    48 => 
    array (
      'format-num-id' => 48,
      'format-pattern' => '##0.0E+0',
      'format-category' => 'number',
    ),
    49 => 
    array (
      'format-num-id' => 49,
      'format-pattern' => '@',
      'format-category' => 'string',
    ),
    44 => 
    array (
      'format-num-id' => 44,
      'format-pattern' => '_-* #,##0.00\\ "₽"_-;\\-* #,##0.00\\ "₽"_-;_-* "-"??\\ "₽"_-;_-@_-',
      'format-category' => '',
    ),
    164 => 
    array (
      'format-num-id' => 164,
      'format-pattern' => '#,##0.00\\ "₽"',
      'format-category' => '',
    ),
    165 => 
    array (
      'format-num-id' => 165,
      'format-pattern' => '[$-F400]h:mm:ss\\ AM/PM',
      'format-category' => 'date',
    ),
    166 => 
    array (
      'format-num-id' => 166,
      'format-pattern' => 'd/m/yy;@',
      'format-category' => 'date',
    ),
  ),
  'fonts' => 
  array (
    0 => 
    array (
      'font-size' => '11',
      'font-color' => '#202020',
      'font-name' => 'Calibri',
      'font-family' => '2',
      'font-scheme' => 'minor',
    ),
    1 => 
    array (
      'font-style-bold' => 1,
      'font-size' => '11',
      'font-color' => '#202020',
      'font-name' => 'Calibri',
      'font-family' => '2',
      'font-charset' => '204',
      'font-scheme' => 'minor',
    ),
  ),
  'fills' => 
  array (
    0 => 
    array (
      'fill-pattern' => 'none',
    ),
    1 => 
    array (
      'fill-pattern' => 'gray125',
    ),
  ),
  'borders' => 
  array (
    0 => 
    array (
      'border-left-style' => NULL,
      'border-right-style' => NULL,
      'border-top-style' => NULL,
      'border-bottom-style' => NULL,
      'border-diagonal-style' => NULL,
    ),
  ),
  'cellStyleXfs' => 
  array (
    0 => 
    array (
      'numFmtId' => 0,
      'fontId' => 0,
      'fillId' => 0,
      'borderId' => 0,
    ),
  ),
  'cellXfs' => 
  array (
    0 => 
    array (
      'numFmtId' => 0,
      'fontId' => 0,
      'fillId' => 0,
      'borderId' => 0,
      'xfId' => 0,
    ),
    1 => 
    array (
      'numFmtId' => 14,
      'fontId' => 0,
      'fillId' => 0,
      'borderId' => 0,
      'xfId' => 0,
    ),
    2 => 
    array (
      'numFmtId' => 0,
      'fontId' => 1,
      'fillId' => 0,
      'borderId' => 0,
      'xfId' => 0,
    ),
    3 => 
    array (
      'numFmtId' => 2,
      'fontId' => 0,
      'fillId' => 0,
      'borderId' => 0,
      'xfId' => 0,
    ),
    4 => 
    array (
      'numFmtId' => 164,
      'fontId' => 0,
      'fillId' => 0,
      'borderId' => 0,
      'xfId' => 0,
    ),
    5 => 
    array (
      'numFmtId' => 44,
      'fontId' => 0,
      'fillId' => 0,
      'borderId' => 0,
      'xfId' => 0,
    ),
    6 => 
    array (
      'numFmtId' => 165,
      'fontId' => 0,
      'fillId' => 0,
      'borderId' => 0,
      'xfId' => 0,
    ),
    7 => 
    array (
      'numFmtId' => 10,
      'fontId' => 0,
      'fillId' => 0,
      'borderId' => 0,
      'xfId' => 0,
    ),
    8 => 
    array (
      'numFmtId' => 12,
      'fontId' => 0,
      'fillId' => 0,
      'borderId' => 0,
      'xfId' => 0,
    ),
    9 => 
    array (
      'numFmtId' => 11,
      'fontId' => 0,
      'fillId' => 0,
      'borderId' => 0,
      'xfId' => 0,
    ),
    10 => 
    array (
      'numFmtId' => 49,
      'fontId' => 0,
      'fillId' => 0,
      'borderId' => 0,
      'xfId' => 0,
    ),
    11 => 
    array (
      'numFmtId' => 166,
      'fontId' => 0,
      'fillId' => 0,
      'borderId' => 0,
      'xfId' => 0,
    ),
    12 => 
    array (
      'numFmtId' => 14,
      'fontId' => 0,
      'fillId' => 0,
      'borderId' => 0,
      'xfId' => 0,
    ),
  ),
);
